### ISSUE TITLE
Issue with missing PCAP magic

### ISSUE THREAD

**Issue by mavam** [kohler/click#135]
I've been generating a PCAP trace with libpcap 1.5.3 and reading it as follows to sort it:

    ipsumdump -r - --collate -w - < trace.pcap > sorted.pcap

It gives me a magic error:

    config:1: While initializing ‘src0 :: FromDump(<stdin>)’:
    <stdin>:   not a tcpdump file (bad magic number)

Looking the beginning of my generated trace with `xxd`, I get this:

    0000000: 4d3c b2a1 0200 0400 0000 0000 0000 0000  M<..............
    0000010: ffff 0000 6500 0000 30a5 044b 3085 3812  ....e...0..K0.8.

So the magic number is `0xa1b23c4d`. In fakepcap.hh, you define:

    #define FAKE_PCAP_MAGIC             0xA1B2C3D4
    #define FAKE_MODIFIED_PCAP_MAGIC	0xA1B2CD34

If the magic does not equal either value, ipsumdump produces the above error. According to the [wireshark wiki](http://wiki.wireshark.org/Development/LibpcapFileFormat), the magic I get should also be okay:

> [..] the writing application writes 0xa1b23c4d, with the two nibbles of the two lower-order bytes swapped, and the reading application will read either 0xa1b23c4d (identical) or 0x4d3cb2a1 (swapped).

This suggest to me that you should add another constant to allow the version with the lower-order bytes swapped, maybe `FAKE_PCAP_MAGIC_SWAPPED`. I'm happy to issue a pull request if you greenlight this change.

**Comment by kohler** [comment]
I'll close this—thanks for actually fixing the issue.
