### ISSUE TITLE
Userlevel FromDevice with PCAP on Ubuntu does not work

### ISSUE THREAD

**Issue by bcronje** [kohler/click#164]
Click team,

Running userlevel Click inside Ubuntu VM and using FromDevice(METHOD PCAP) results in ~99 - 100% packet drops. Using METHOD LINUX works 100%.

Tcpdump on this same VM works fine, so I'm assuming there is an issue on the async IO side.

The issue seems to be only on Ubuntu (tested  with 14.04.1 and 14.10 on virtual machine), testing with CentOS using the exact same Click setup and config everything works fine.

Has anyone else experienced this as well?
Any pointers how to debug this further?
Could there be some kernel setting that affects PCAPs async processing on Ubuntu?

**Comment by asridharan** [comment]
Have been running userlevel click with netmap (not libpcap) on gentoo VMs
(kernel 3.14.4) and works fine. This works only with the emulated drivers
(e1000, r8139). Userlevel click with netmap over virtio drivers have issues
(virtio headers aren't being stripped at this point).

When you say there are ~99-100% drop, where are the drops occuring? Also
assuming you are using the latest click (from gitHub) ?

-Avinash

**Comment by bcronje** [comment]
Drops are occurring somewhere inside libpcap or scheduling of select or somewhere similar. That is, packets never even reach Click. Essentially FromDevice's kernel_drops counter increases at a steady rate as packets are supposed to be received. Packet rate is not an issue as the tests only send a ping request to the VM, where Click will respond with an ARP response and icmp response using the following config:

    fd::FromDevice(eth0, METHOD PCAP);
    td::Queue -> ToDevice(eth0, METHOD PCAP);
    ar :: ARPResponder(10.51.1.104 08:00:27:51:96:e3);
    
    fd -> c :: Classifier(12/0806 20/0001, 12/0800);
    c[0] -> ar
    c[1] -> CheckIPHeader(14) -> ipc::IPClassifier(dst host 10.51.1.104) -> ping::IPClassifier(icmp type echo);
    ping[0] -> ICMPPingResponder -> EtherMirror -> td;
    ar -> td;

If we change `METHOD PCAP` to `METHOD LINUX` then everything works as expected.

Couple of other points:
1. This only happens when we tested on Ubuntu (14.04.1 and 14.10). CentOS 7 works fine with PCAP and the same config.
2. Results are the same in sniffer mode and non-sniffer mode. In sniffer mode when run alongside tcpdump we can actually see the arp/icmp packets coming into the server, but it never gets to Click. I'm assuming tcpdump uses PCAP in blocking/synchronous mode, where Click uses async mode. Hence my hunch around something being fault with Ubuntu's handling PCAPs async operations.
3. Yes we are running latest github code.

**Comment by bcronje** [comment]
Never found the root cause here. Moved over to CentOS for dev box that doesn't display this issue.

**Comment by kohler** [comment]
I reopened this because I got a chance to look at it on an ubuntu VM. Commit a9a0887b9e5c3eca57c5b17ad3d242f09d8e87ac should address this; let me know if you have a chance to look at it.

**Comment by bcronje** [comment]
Eddie, had a chance to look at this again. Commit a9a0887 seems like a step in the right direction, that is I'm not seeing drops any more using the ping test config above. However there is definitely still something wrong as ping response from Click from another machine is really high. Some test output, ping from Windows to local guest Ubuntu VM running latest Click and test config above:

**FromDevice with METHOD PCAP**
    Pinging 10.51.1.104 with 32 bytes of data:
    Reply from 10.51.1.104: bytes=32 time=403ms TTL=255
    Reply from 10.51.1.104: bytes=32 time=2300ms TTL=255
    Reply from 10.51.1.104: bytes=32 time=431ms TTL=255
    Reply from 10.51.1.104: bytes=32 time=462ms TTL=255

**FromDevice with METHOD LINUX**
    Pinging 10.51.1.104 with 32 bytes of data:
    Reply from 10.51.1.104: bytes=32 time<1ms TTL=255
    Reply from 10.51.1.104: bytes=32 time<1ms TTL=255
    Reply from 10.51.1.104: bytes=32 time<1ms TTL=255
    Reply from 10.51.1.104: bytes=32 time<1ms TTL=255

So it appears as if the packets are only processed after some time has passed using the PCAP method. I've test this with libpcap 1.5.3-2 and latest libpcap 1.7.3 and both versions on Ubuntu based distro behaved the same.

Any idea what's up with that?

Again, Centos with libpcap 1.5.3 does not exhibit any of this and works as expected with PCAP.

**Comment by bcronje** [comment]
Looks like others are starting to see this issue as well. See http://librelist.com/browser//click/2015/6/23/problem-with-pcap-dispatch-in-userlevel-fromdevice-cc/

Interesting link from that mail was the following libpcap bug and subsequent patch which might be related to the issues we're seeing in Click:

https://github.com/the-tcpdump-group/libpcap/issues/350

https://github.com/the-tcpdump-group/libpcap/commit/9e35faaac7436d29b607e5664b73c4676ec326a4

**Comment by MappaM** [comment]
I'll try to reproduce the problem here. Do you have a minimal reproductible click configuration (burst and other parameters)?

**Comment by martinjreed** [comment]
Hi, I was the recent poster http://librelist.com/browser//click/2015/6/23/problem-with-pcap-dispatch-in-userlevel-fromdevice-cc/
I just tried libpcap-1.8.0 using the latest git sources and the bug is still present. It is difficult for me to share the fault to reproduce it as it is a whole project of code and I have not a simple example yet. I hope to provide a simple example (or work out a fix) some time in the next month.

**Comment by martinjreed** [comment]
Just emailed the list as it seems to be solved with a kernel upgrade to 3.19 and reading the libpcap comments this is to be expected as a problem on any kernel <3.19

**Comment by bcronje** [comment]
@martinjreed that is good news. I'll do some test on my side after upgrading kernel and report back. Wont be before the weekend though.
