### ISSUE TITLE
Error during build.

### ISSUE THREAD

**Issue by bjooris** [kohler/click#171]
Hi all,

just did a git pull. With this config ./configure --enable-linuxmodule --enable-userlevel --enable-all-elements --enable-wifi

I've got this error during the make:
...
  CXX [M] config.o
  CXX [M] sched.o
  CXX [M] module.o
  CXX [M] clickfs.o
  CXX [M] skbmgr.o
  CXX [M] elements.o
/usr/local/11ac/click/linuxmodule/skbmgr.cc:229:57: error: no ‘unsigned int RecycledSkbPool::size_to_lower_bucket_size(unsigned int)’ member function declared in class ‘RecycledSkbPool’
 RecycledSkbPool::size_to_lower_bucket_size(unsigned size)
                                                         ^
make[3]: *** [/usr/local/11ac/click/linuxmodule/skbmgr.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/local/11ac/click/linuxmodule/../elements/grid/dsdvroutetable.hh:7:0,
                 from /usr/local/11ac/click/linuxmodule/elements.cc:50:
/usr/local/11ac/click/linuxmodule/../elements/grid/grid.hh: In member function ‘String grid_location::s() const’:
/usr/local/11ac/click/linuxmodule/../elements/grid/grid.hh:62:65: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int32_t {aka int}’ [-Wformat=]
     snprintf(buf, 255, "%ld,%ld,%ld", lat_ms(), lon_ms(), h_mm());
                                                                 ^
/usr/local/11ac/click/linuxmodule/../elements/grid/grid.hh:62:65: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘int32_t {aka int}’ [-Wformat=]
/usr/local/11ac/click/linuxmodule/../elements/grid/grid.hh:62:65: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 6 has type ‘int32_t {aka int}’ [-Wformat=]
make[2]: *** [_module_/usr/local/11ac/click/linuxmodule] Error 2
make[2]: Leaving directory `/usr/src/linux-headers-3.13.0-33-generic'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/local/11ac/click/linuxmodule'
make: *** [linuxmodule] Error 2

Thanks in advance,

Bart

**Comment by bjooris** [comment]
commit 9eb64b0cb8117e0dfe1c1f162c0af7e259643fa9 builds ok.

Thanks,

Bart

**Comment by kohler** [comment]
Fixed in 24d575b, thanks for the report!
