### ISSUE TITLE
Low limit on SNAPLEN

### ISSUE THREAD

**Issue by sga001** [kohler/click#179]
The size limit on `_snaplen` in `elements/userlevel/fromdevice.cc (line 108)` seems low (`8190`) and inconsistent with pcap's recommended limit (`65535`). I consistently encountered `CheckIPHeader` issues because of "bad IP length" as a result of big IP packets that were not being fully captured (even when I set `SNAPLEN` to the current maximum of `8190`). Increasing the limit solved all my issues.

**Comment by kohler** [comment]
That's been there since 2000—doubt the limit was there for any good reason. Set to 65535 as you suggest, thanks.
