### ISSUE TITLE
Running maz-nat in userspace

### ISSUE THREAD

**Issue by muradkablan** [kohler/click#186]
Hi Eddie,
I need to run maz-nat in userspace and I'm having a problem with TCP. Yes, I know kernel space gives much much better performance. But we are in the process of integrating Click with another project and we must run Click in userspce. 

Using the same configuration file in Click repo, I could use it in kernelspace with full link BW. When I switched to userspace, I had to modify the configuration file by changing ToHost element to ToHost(tap0) since the first one only works in linuxmode. With theses changes, I can only test iperf in UDP between two end hosts and of course click running maz-nat in a machine resides in the middle.

Now, the only way I could make the two end hosts reach each other with tcp is by disabling ARP in the interfaces in the machine running click. When ARP is off, Click seems to respond to arp queries.  I wrote a simple tcp client/server program and was able to connect them and send some packets between them (through click-nat of course).

The main problem is when I want to run tcp iperf. When the connection is established between the two ends, Click shows this error "CheckIPHeader@37: IP header check failed: bad IP length".
After the test is done. Both ends report BW with 70Kbit. Which is about one packet. 
Looking at Wireshark at the machine running NAT, it seems that Client keep retransmitting a packet over and over. 

I am guessing the problem is related to ARP since it is the only thing changed in config file and also the tcp handshake since click shows the error above.
  
Any suggestions?

Thanks alot

Murad

**Comment by pallas** [comment]
Can you post an example click config? You probably need to add an IPClassifier to filter out ARP if the Host is responding or to divert those packets to Elements that can if the Host is not responding. You're right about there being differences between userland and linuxmodule, and one of those differences is the way ARP is handled. I'm surprised you didn't have to implement an ARPTable + ARPQuerier + ARPResponder before but without a click config it is hard to say.

**Comment by muradkablan** [comment]
Thanks for the reply. Attached is the config file in the second comment (I didn't know how to attach it here). 
Some clarifications about the setup:
1- The machine running click has two interfaces br1 and br2 with each in a different network 10.15.0.0/24 and 10.17.0.0/24 respectively. Click machine is connected directly to the two end hosts. There is no gateway or extern-network as in original maz-nat.

2- Traffic should be forwarded from 10.15.0.0(internal network)  to 10.17.0.0 (external network).

3- That said,  EtherEncap(0x0800, b8:2a:72:dd:5a:c9, 00:30:1b:bd:6b:6f) in line 80 encapsulate src MAC with br2 MAC and dst MAC with the external machine running iperf -s.

4- tap0 is created by running
sudo ip tuntap add dev tap0 mode tap user murad
But it is not attached to anything. I wasn't sure to where I should attach it.

Thanks again,
Muad

**Comment by muradkablan** [comment]
// ADDRESS INFORMATION

AddressInfo(
  intern        10.15.0.1       10.15.0.0/24    b8:2a:72:dd:5a:c8,
  extern        10.17.0.1       10.17.0.0/24    b8:2a:72:dd:5a:c9,
  intern_server 10.15.0.3
);


// DEVICE SETUP

elementclass GatewayDevice {
  $device |
  from :: FromDevice($device, SNIFFER false)
        -> output;
  input -> q :: Queue(1024)
        -> to :: ToDevice($device);
  ScheduleInfo(from .1, to 1);
}

FromHost(tap0) -> Discard;

//extern_dev :: GatewayDevice(extern:eth);
//intern_dev :: GatewayDevice(intern:eth);

extern_dev :: GatewayDevice(br2);
intern_dev :: GatewayDevice(br1);

ip_to_host :: EtherEncap(0x0800, 1:1:1:1:1:1, intern) // -> IPPrint(to_host) 
        -> ToHost(tap0);


// ARP MACHINERY

extern_arp_class, intern_arp_class
        :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);
intern_arpq :: ARPQuerier(intern);

extern_dev -> extern_arp_class;
extern_arp_class[0] -> ARPResponder(extern)     // ARP queries
        -> extern_dev;
extern_arp_class[1] -> ToHost(tap0);                     // ARP responses
extern_arp_class[3] -> Discard;

intern_dev -> intern_arp_class;
intern_arp_class[0] -> ARPResponder(intern)     // ARP queries
        -> intern_dev;
intern_arp_class[1] -> intern_arpr_t :: Tee;
        intern_arpr_t[0] -> ToHost(tap0);
        intern_arpr_t[1] -> [1]intern_arpq;
intern_arp_class[3] -> Discard;


// REWRITERS

IPRewriterPatterns(to_world_pat extern 65533 - -,
                to_server_pat intern 50000-65535 intern_server -);

rw :: IPRewriter(// internal traffic to outside world
                 pattern to_world_pat 0 1,
                 // external traffic redirected to 'intern_server'
                 pattern to_server_pat 1 0,
                 // internal traffic redirected to 'intern_server'
                 pattern to_server_pat 1 1,
                 // virtual wire to output 0 if no mapping
pattern to_world_pat 0 1,
                 // virtual wire to output 2 if no mapping
                 pass 2);

tcp_rw :: TCPRewriter(// internal traffic to outside world
                pattern to_world_pat 0 1,
                // everything else is dropped
                drop);


// OUTPUT PATH

ip_to_extern :: GetIPAddress(16)
      -> CheckIPHeader 
      -> EtherEncap(0x0800, b8:2a:72:dd:5a:c9, 00:30:1b:bd:6b:6f) 
      //-> IPPrint(To-ExternDev-AfterCheck-and-Encap)
      -> extern_dev;
ip_to_intern :: GetIPAddress(16)
      -> CheckIPHeader
      -> [0]intern_arpq
      //-> IPPrint(To-InternDev-AfterCheck)
      -> intern_dev;


// to outside world or gateway from inside network
rw[0] -> ip_to_extern_class :: IPClassifier(dst host intern, -);
  ip_to_extern_class[0] -> ip_to_host;
  ip_to_extern_class[1] -> ip_to_extern;
// to server
rw[1] -> ip_to_intern;
// only accept packets from outside world to gateway
rw[2] -> IPClassifier(dst host extern) //-> IPPrint(from-rw2-to-ip_to_host)
        -> ip_to_host;

// tcp_rw is used only for FTP control traffic
tcp_rw[0] -> ip_to_extern;
tcp_rw[1] -> ip_to_intern;


// FILTER & REWRITE IP PACKETS FROM OUTSIDE

ip_from_extern :: IPClassifier(dst host extern,
                        -);
my_ip_from_extern :: IPClassifier(dst tcp ssh,
                        dst tcp www or https,
                        src tcp port ftp,
                        tcp or udp,
                        -);

extern_arp_class[2] -> Strip(14)
        -> CheckIPHeader
        -> ip_from_extern;
ip_from_extern[0] -> my_ip_from_extern;
  my_ip_from_extern[0] -> [1]rw; // SSH traffic (rewrite to server)
  my_ip_from_extern[1] -> [1]rw; // HTTP(S) traffic (rewrite to server)
  my_ip_from_extern[2] -> [1]tcp_rw; // FTP control traffic, rewrite w/tcp_rw
  my_ip_from_extern[3] -> [4]rw; // other TCP or UDP traffic, rewrite or to gw
  my_ip_from_extern[4] -> Discard; // non TCP or UDP traffic is dropped
ip_from_extern[1] -> Discard;   // stuff for other people


// FILTER & REWRITE IP PACKETS FROM INSIDE

ip_from_intern :: IPClassifier(dst host intern,
                        dst net intern,
			dst tcp port ftp,
                        -);
my_ip_from_intern :: IPClassifier(dst tcp ssh,
                        dst tcp www or https,
                        src or dst port dns,
                        dst tcp port auth,
                        tcp or udp,
                        -);

intern_arp_class[2] -> Strip(14)
        -> CheckIPHeader   
        -> ip_from_intern;
ip_from_intern[0] -> my_ip_from_intern; // stuff for 10.0.0.1 from inside
  my_ip_from_intern[0] -> ip_to_host; // SSH traffic to gw
  my_ip_from_intern[1] -> [2]rw; // HTTP(S) traffic, redirect to server instead
  my_ip_from_intern[2] -> Discard;  // DNS (no DNS allowed yet)
  my_ip_from_intern[3] -> ip_to_host; // auth traffic, gw will reject it
  my_ip_from_intern[4] -> [3]rw; // other TCP or UDP traffic, send to linux
                                // but pass it thru rw in case it is the
                                // returning redirect HTTP traffic from server
  my_ip_from_intern[5] -> ip_to_host; // non TCP or UDP traffic, to linux
ip_from_intern[1] -> ip_to_host; // other net 10 stuff, like broadcasts
ip_from_intern[2] -> Print(FTP-pckt-to-be-discarded) //FTPPortMapper(tcp_rw, rw, 0)
                -> [0]tcp_rw;   // FTP traffic for outside needs special
                                // treatment
ip_from_intern[3] -> [0]rw;     // stuff for outside

**Comment by muradkablan** [comment]
Updates
We have been working on running tcp iperf and cleaned up the config file to narrow down the problem. We can run tcp connection through Click NAT and stream small packets. I cleaned up the ARP handling and I can see that Click successfully responses to ARP guiries with the right MAC address. 

We believe the problem raises when it comes to stream packers larger than 400 Bytes through Click (we tested with iperf, netperf, and i-dtg). Click in userspace seems to have a bug/unable to handle packets above 400 bytes and misses up checksum and IP header check. Resulting with packets have actual length that is different than what its stated in the header, thus resulting Click to drop the packets when its checks IP header and produce the previous error mentioned "CheckIPHeader@37: IP header check failed: bad IP length".

We tried to change the behavior to not drop the packets even if the checksome failed. But ToDevice element did not like the packet when it arrived to it and produced "Message too long" error.

**Comment by muradkablan** [comment]
// Updated config file
// ADDRESS INFORMATION

AddressInfo(
  intern        10.15.0.1       10.15.0.0/24    b8:2a:72:dd:5a:c8,
  extern        10.17.0.1       10.17.0.0/24    b8:2a:72:dd:5a:c9,
  extern_next_hop                               00:30:1b:bd:1b:1f,
  intern_server 10.15.0.3
);


// DEVICE SETUP

elementclass GatewayDevice {
  $device |
  from :: FromDevice($device, SNIFFER false)
        -> output;
  input -> q :: Queue(1024)
        -> to :: ToDevice($device);
  ScheduleInfo(from .1, to 1);
}

FromHost(tap0) -> Discard;

extern_dev :: GatewayDevice(br2);
intern_dev :: GatewayDevice(br1);

ip_to_host :: EtherEncap(0x0800, 1:1:1:1:1:1, intern) 
        -> ToHost(tap0);


// ARP MACHINERY

extern_arp_class, intern_arp_class
	  :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);

extern_dev -> extern_arp_class;
extern_arp_class[0]  -> ARPResponder(extern) 
	-> ARPPrint(ARP-R-Ext, ETHER true)    // ARP queries
        -> extern_dev;
extern_arp_class[1] -> Discard; //ToHost(tap0);                     // ARP responses
extern_arp_class[3] -> Discard;

intern_dev -> intern_arp_class;
intern_arp_class[0] -> ARPResponder(intern)     // ARP queries
	-> ARPPrint(ARP-R-Int, ETHER true)
        -> intern_dev;
intern_arp_class[1] -> Discard; //ToHost(tap0);
intern_arp_class[3] -> Discard;


// REWRITERS

IPRewriterPatterns(to_world_pat extern 65533 - -,
                to_server_pat intern 50000-65535 intern_server -);

rw :: IPRewriter(// internal traffic to outside world
                 pattern to_world_pat 0 1,
                 // external traffic redirected to 'intern_server'
                 pattern to_server_pat 1 0,
                 // internal traffic redirected to 'intern_server'
                 pattern to_server_pat 1 1,
                 // virtual wire to output 0 if no mapping
pattern to_world_pat 0 1,
                 // virtual wire to output 2 if no mapping
                 pass 2);

tcp_rw :: TCPRewriter(// internal traffic to outside world
                pattern to_world_pat 0 1,
                // everything else is dropped
                drop);


// OUTPUT PATH

ip_to_extern :: GetIPAddress(16)
      -> CheckIPHeader //-> IPPrint(OUTgr-toExt-BeforEnacp)
      -> EtherEncap(0x0800, b8:2a:72:dd:5a:c9, 00:30:1b:bd:6b:6f) //-> IPPrint(OUTgr-toExt-AfterEnacp)
      -> extern_dev;
ip_to_intern :: GetIPAddress(16)
      -> CheckIPHeader //-> IPPrint(OUTgr-toInt-BeforEnacp)
      -> EtherEncap(0x0800, b8:2a:72:dd:5a:c8, bc:5f:f4:ac:52:ce) //-> IPPrint(OUTgr-toInt-AfterEnacp)
      -> intern_dev;


// to outside world or gateway from inside network
rw[0] -> ip_to_extern_class :: IPClassifier(dst host intern, -);
  ip_to_extern_class[0] -> ip_to_host;
  ip_to_extern_class[1] -> ip_to_extern;
// to server
rw[1] -> ip_to_intern;
// only accept packets from outside world to gateway
rw[2] -> IPClassifier(dst host extern) //-> IPPrint(from-rw2-to-ip_to_host)
        -> ip_to_host;

// tcp_rw is used only for FTP control traffic
tcp_rw[0] -> ip_to_extern;
tcp_rw[1] -> ip_to_intern;


// FILTER & REWRITE IP PACKETS FROM OUTSIDE

ip_from_extern :: IPClassifier(dst host extern,
                        -);
my_ip_from_extern :: IPClassifier(dst tcp ssh,
                        dst tcp www or https,
                        src tcp port ftp,
                        tcp or udp,
                        -);

extern_arp_class[2] -> Strip(14)
        -> CheckIPHeader //-> IPPrint(ingress-from-extNet)
        -> ip_from_extern;
ip_from_extern[0] -> my_ip_from_extern;
  my_ip_from_extern[0] -> [1]rw; // SSH traffic (rewrite to server)
  my_ip_from_extern[1] -> [1]rw; // HTTP(S) traffic (rewrite to server)
  my_ip_from_extern[2] -> [1]tcp_rw; // FTP control traffic, rewrite w/tcp_rw
  my_ip_from_extern[3] -> [4]rw; // other TCP or UDP traffic, rewrite or to gw
  my_ip_from_extern[4] -> Discard; // non TCP or UDP traffic is dropped
ip_from_extern[1] -> Discard;   // stuff for other people


// FILTER & REWRITE IP PACKETS FROM INSIDE

ip_from_intern :: IPClassifier(dst host intern,
                        dst net intern,
			dst tcp port ftp,
                        -);
my_ip_from_intern :: IPClassifier(dst tcp ssh,
                        dst tcp www or https,
                        src or dst port dns,
                        dst tcp port auth,
                        tcp or udp,
                        -);

intern_arp_class[2] -> Strip(14)
        -> CheckIPHeader //-> IPPrint(ingress-from-intNet)  
        -> ip_from_intern;
ip_from_intern[0] -> my_ip_from_intern; // stuff for 10.0.0.1 from inside
  my_ip_from_intern[0] -> ip_to_host; // SSH traffic to gw
  my_ip_from_intern[1] -> [2]rw; // HTTP(S) traffic, redirect to server instead
  my_ip_from_intern[2] -> Discard;  // DNS (no DNS allowed yet)
  my_ip_from_intern[3] -> ip_to_host; // auth traffic, gw will reject it
  my_ip_from_intern[4] -> [3]rw; // other TCP or UDP traffic, send to linux
                                // but pass it thru rw in case it is the
                                // returning redirect HTTP traffic from server
  my_ip_from_intern[5] -> ip_to_host; // non TCP or UDP traffic, to linux
ip_from_intern[1] -> ip_to_host; // other net 10 stuff, like broadcasts
ip_from_intern[2] -> Print(FTP-pckt-to-be-discarded) //FTPPortMapper(tcp_rw, rw, 0)
                -> [0]tcp_rw;   // FTP traffic for outside needs special
                                // treatment
ip_from_intern[3] -> [0]rw;     // stuff for outside

**Comment by muradkablan** [comment]
Since we believe the problem is more related to Click itself not maz config file, I am going to open a new issue for it.

**Comment by ahenning** [comment]
Hi Murad,

This is most likely not a click bug, but segmentation offloading built into the NIC. You can use something like CheckLength -> Print to confirm. The driver aggregates packets resulting in packets >2000 bytes causing the invalid header checks and message too long errors. Its not helpful anyway for your router implementation.

Use ethtool to disable segmentation offloading e.g.

ethtool --offload eth0 tso off    
ethtool --offload eth0 gso off    
ethtool --offload eth0 gro off

**Comment by muradkablan** [comment]
Thanks for your reply,
Just to clarify, when you say "driver aggregates packets". Do you mean at the sender machine (generator of traffic)? or the machine running click?

The two end hosts connected to machine running click in a small setup with 1G links. With UDP we can get maximum of 812Mbit throughput. Do you have an estimate what it the maximum BW we can achieve with Click in userspace with the above issue in NIC?

Thanks again.

**Comment by ahenning** [comment]
On the interfaces used in the click config.

The segmentation offloading will not severely affect throughput, but once you can process 1500 byte packets, the overhead per packet will be less and throughput will be closer to 1Gbps.

**Comment by muradkablan** [comment]
Awesome!
I made the changes you mentioned above with ethtool and I can get 896Mbit.

Thank you so much :)
Murad

**Comment by ahenning** [comment]
Great, pleasure.
