### ISSUE TITLE
Click not compiling on version 12.04

### ISSUE THREAD

**Issue by talalahmad** [kohler/click#190]
I am trying to install click. This is where it is getting stuck:

  CC [M] ksyms.o
  CC [M]  /home/user/click/linuxmodule/proclikefsmod.o
/home/user/click/linuxmodule/proclikefs.c: In function ‘proclikefs_unregister_filesystem’:
/home/user/click/linuxmodule/proclikefs.c:335:1: warning: the frame size of 1152 bytes is larger than 1024 bytes [-Wframe-larger-than=]
  LD [M]  /home/user/click/linuxmodule/click.o
`.text._ZN7Storage8set_headEj' referenced in section `.altinstructions' of /home/user/click/linuxmodule/fromhost.o: defined in discarded section `.text._ZN7Storage8set_headEj[_ZN7Storage8set_headEj]' of /home/user/click/linuxmodule/fromhost.o
make[3]: *** [/home/user/click/linuxmodule/click.o] Error 1
make[2]: *** [_module_/home/user/click/linuxmodule] Error 2
make[2]: Leaving directory `/usr/src/linux-headers-3.13.0-49-generic'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/user/click/linuxmodule'
make: *** [install-linuxmodule] Error 2

**Comment by chuanic** [comment]
try this:
./configure --enable-userlevel --disable-linuxmodule

**Comment by hsysuper** [comment]
This fix the error but also disabled the linux module. How do we fix the error without --disable-linuxmodule?
