### ISSUE TITLE
Replace Click mailing list with Github Issues?

### ISSUE THREAD

**Issue by bcronje** [kohler/click#201]
I'd like to propose that Click's Github Issues replace the Click mailing list. Apart from the fact that I (and presumably others) are having major issues subscribing to and staying on the Click librelist, as it keeps dropping me off the list for some reason, Github Issues just seems like a more modern approach.

Also I see some people are still using the old mailing list, been trying to forward to librelist but again I find it impossible to stay on the list.

What are your feelings around this?

**Comment by asridharan** [comment]
The only problem I see with using Github issues as a discussion forum
(which is what mailing lists exist for) is that it will confuse the main
objective of Github issues, that of bug tracking and patch requests.

**Comment by kohler** [comment]
I agree about the discussion problem. But it's not like the discussion content is that active at the moment.

Looks to me like librelist was an unfortunate choice, and we should find a better one. All the cool kids use IRC but I won't.

**Comment by MappaM** [comment]
I've got mailing list problems too. I don't get e-mails from some people (noticed at least with Antonie Henning). I've got to wait for someone to respond or go from time to time to the archives on http://librelist.com/browser/click/ . But at least I stay subscribed...
