### ISSUE TITLE
Kernel BUG when setting Priority Level in click-install

### ISSUE THREAD

**Issue by yahyaezzeldin** [kohler/click#207]
Hi,
I am encoutering a problem when trying to install a click configuration with click-install and setting a priority level. For example, running "click-install --priority=19 configuration.click" gives me the following error while "click-install configuration.click" goes through with no problems. (Any number, not necessarily 19 gives me an error)

TRACE FROM dmesg:

[  142.612110] click: starting router thread pid 2477 (ffff8800a3c9db00)
[  142.612583] BUG: unable to handle kernel NULL pointer dereference at 0000000000000060
[  142.612670] IP: [<ffffffffa06f3588>] handler_do_write.isra.25+0x4b8/0xb90 [click]
[  142.612855] PGD 9dd29067 PUD 9dd28067 PMD 0 
[  142.612893] Oops: 0000 [#1] SMP 
[  142.612924] Modules linked in: click(OF) proclikefs(OF) ctr ccm snd_hda_codec_hdmi btusb rfcomm bnep bluetooth acer_wmi sparse_keymap uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_core videodev arc4 snd_hda_codec_realtek iwldvm mac80211 coretemp snd_hda_intel snd_hda_codec snd_hwdep snd_pcm joydev snd_seq_midi serio_raw snd_seq_midi_event snd_rawmidi lpc_ich iwlwifi cfg80211 radeon snd_seq snd_page_alloc wmi ttm drm_kms_helper drm snd_seq_device snd_timer video snd i2c_algo_bit soundcore mac_hid parport_pc ppdev lp parport hid_generic usbhid hid psmouse ahci libahci tg3 ptp pps_core
[  142.613439] CPU: 0 PID: 2471 Comm: click-install Tainted: GF          O 3.13.0-32-generic #57-Ubuntu
[  142.613487] Hardware name: Acer            Aspire 5738                    /JV50                           , BIOS V1.21           10/23/2009
[  142.613543] task: ffff8800a5cedfc0 ti: ffff880099e10000 task.ti: ffff880099e10000
[  142.613576] RIP: 0010:[<ffffffffa06f3588>]  [<ffffffffa06f3588>] handler_do_write.isra.25+0x4b8/0xb90 [click]
[  142.613710] RSP: 0018:ffff880099e11df0  EFLAGS: 00010202
[  142.613740] RAX: 0000000000000000 RBX: ffff8800afea2290 RCX: ffff8800aeb26a58
[  142.613772] RDX: 0000000240000051 RSI: 00000000ffffffff RDI: 0000000000000000
[  142.613804] RBP: ffff880099e11f00 R08: 0000000000952100 R09: 00007f3ac2221780
[  142.613837] R10: 00007f3ac15f26a0 R11: 0000000000000246 R12: 00000000fffffffb
[  142.613869] R13: ffff88009ddce680 R14: 0000000000000000 R15: 000000000094c9a0
[  142.613901] FS:  00007f3ac2221780(0000) GS:ffff88013fc00000(0000) knlGS:0000000000000000
[  142.613944] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  142.613971] CR2: 0000000000000060 CR3: 00000000aa674000 CR4: 00000000000407f0
[  142.614003] Stack:
[  142.614017]  ffffffff811a170e 0000000000000000 0000000000000000 0000000000000000
[  142.614067]  0000000000000000 ffff880099e11e28 ffffffff8101b773 ffff880099e11e38
[  142.614116]  ffff880099e11e40 ffffffff8101b773 ffff880099e11e50 ffffffff8101b7e9
[  142.614167] Call Trace:
[  142.614185]  [<ffffffff811a170e>] ? __kmalloc+0x2e/0x230
[  142.614217]  [<ffffffff8101b773>] ? native_sched_clock+0x13/0x80
[  142.614250]  [<ffffffff8101b773>] ? native_sched_clock+0x13/0x80
[  142.614283]  [<ffffffff8101b7e9>] ? sched_clock+0x9/0x10
[  142.614315]  [<ffffffff8109d1ad>] ? sched_clock_local+0x1d/0x80
[  142.614345]  [<ffffffff8111155c>] ? acct_account_cputime+0x1c/0x20
[  142.614379]  [<ffffffff8109d7db>] ? account_user_time+0x8b/0xa0
[  142.614492]  [<ffffffffa06f3cb6>] handler_flush+0x56/0x60 [click]
[  142.614524]  [<ffffffff811ba10f>] filp_close+0x2f/0x70
[  142.614559]  [<ffffffff811da6fb>] __close_fd+0x7b/0xa0
[  142.614591]  [<ffffffff811ba173>] SyS_close+0x23/0x50
[  142.614619]  [<ffffffff8172c87f>] tracesys+0xe1/0xe6
[  142.614650] Code: 76 a0 c7 85 48 ff ff ff 00 00 00 00 48 c7 85 50 ff ff ff 00 00 00 00 0f 84 b4 fc ff ff 45 8b 7d 08 e9 c5 fc ff ff 0f 1f 44 00 00 <48> 8b 40 60 48 89 85 f8 fe ff ff f0 ff 40 18 48 c7 c7 40 f6 7a 
[  142.615027] RIP  [<ffffffffa06f3588>] handler_do_write.isra.25+0x4b8/0xb90 [click]
[  142.615159]  RSP <ffff880099e11df0>
[  142.615176] CR2: 0000000000000060
[  142.621134] ---[ end trace 4687a48300bce60d ]---

I am not using anything apart from the normal elements, the configuration file is :

define($server 143.205.176.132);
phyint :: FromDevice(wlan0);
EtherClassify :: Classifier (12/0800,-); // 0800 in the 12th-13th byte,means its an IP Frame
EtherClassify[1] -> ToHost(wlan0); 
NtwClassify :: IPClassifier($server/32 tcp,-);
NtwClassify[1] -> Unstrip(14) -> ToHost(wlan0);

phyint  -> EtherClassify[0] -> Strip(14) //Manual strip of ETHER Header (no Element)
        -> CheckIPHeader() ->  NtwClassify[0]
        -> Unstrip(14) -> ToHost(wlan0);

How do I fix this ?

P.S. : I am actually trying to give my click kernel thread a higher priority to get delay accuracy in DelayUnqueue with less than 50microseconds error.

**Comment by kohler** [comment]
I think this is fixed by ad9bc3b. Thanks for reporting it.

**Comment by yahyaezzeldin** [comment]
Yes it is working now.

Thank you
