### ISSUE TITLE
click-install not working

### ISSUE THREAD

**Issue by doantungbk** [kohler/click#216]
Hi everyone,
I have a serious problem which i spent some days to fix. Please help me solve this problem. When i run some file *.click under linuxmodule mode, I got a report:

oneclick@oneclick:~/click/conf$ click-install mazu-nat.click
insmod: error inserting '/usr/local/lib/proclikefs.ko': -1 Operation not permitted
click-install: '/sbin/insmod /usr/local/lib/proclikefs.ko' failed

My ubuntu version is 10.04 (Kernel version: 2.6.32-38-generic). How can I fix this?
I wish all you have a nice day!

**Comment by tbarbette** [comment]
Did you try with sudo?

**Comment by doantungbk** [comment]
Thank you very much for your quick respone!  It is so easy but i forgot, It works now, but i do not know if it is correct. Do i have to activate ethernet first, right?
----------------------------------------
oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click
mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'extern:eth' is down
oneclick@oneclick:~/click/conf$ sudo click-install udp-gen.click
udp-gen.click: No such file or directory
oneclick@oneclick:~/click/conf$ sudo click-install test.click
test.click:19: While configuring 'CheckIPHeader@4 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click
mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'extern:eth' is down
--------------------------------------

**Comment by doantungbk** [comment]
Thank you very much for your quick response, Mr Tbarbette!. It is so easy but i forgot. It works now, however i do not know if it is correct. I have to activate ethernet first, right?
-----------------
oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click
[sudo] password for oneclick: 
mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'extern:eth' is down
oneclick@oneclick:~/click/conf$ sudo click-install udp-gen.click
udp-gen.click: No such file or directory
oneclick@oneclick:~/click/conf$ sudo click-install test.click
test.click:19: While configuring 'CheckIPHeader@4 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click
mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice':
  warning: device 'extern:eth' is down
mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice':
  warning: device 'intern:eth' is down
mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
  warning: device 'extern:eth' is down
-----------------------------

**Comment by doantungbk** [comment]
Thank you very much for your quick response, Mr Tbarbette!. It is so easy but i forgot. It works now, however i do not know if it is correct. I have to activate ethernet first, right?
-------------------------------------
oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click
[sudo] password for oneclick:
mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice':
warning: device 'extern:eth' is down
mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice':
warning: device 'intern:eth' is down
mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice': warning: device 'extern:eth' is down mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice': warning: device 'intern:eth' is down mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'extern:eth' is down
oneclick@oneclick:~/click/conf$ sudo click-install udp-gen.click
udp-gen.click: No such file or directory
oneclick@oneclick:~/click/conf$ sudo click-install test.click
test.click:19: While configuring 'CheckIPHeader@4 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice': warning: device 'extern:eth' is down mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice': warning: device 'intern:eth' is down mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice':
warning: device 'extern:eth' is down
mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice':
warning: device 'intern:eth' is down
mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through `click-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'extern:eth' is down
-------------------------------------------------

**Comment by doantungbk** [comment]
Thank you very much for your quick response, Mr Tbarbette!. It is so easy but i forgot. It works now, however i do not know if it is correct. I have to activate ethernet first, right?
oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click
[sudo] password for oneclick:
mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice':
warning: device 'extern:eth' is down
mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice':
warning: device 'intern:eth' is down
mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice': warning: device 'extern:eth' is down mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice': warning: device 'intern:eth' is down mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'extern:eth' is down
oneclick@oneclick:~/click/conf$ sudo click-install udp-gen.click
udp-gen.click: No such file or directory
oneclick@oneclick:~/click/conf$ sudo click-install test.click
test.click:19: While configuring 'CheckIPHeader@4 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) oneclick@oneclick:~/click/conf$ sudo click-install mazu-nat.click mazu-nat.click:83: While configuring 'extern_dev/to :: ToDevice': warning: device 'extern:eth' is down mazu-nat.click:83: While configuring 'intern_dev/to :: ToDevice': warning: device 'intern:eth' is down mazu-nat.click:146: While configuring 'CheckIPHeader@23 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:177: While configuring 'CheckIPHeader@29 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through click-align'.) mazu-nat.click:202: While configuring 'CheckIPHeader@35 :: CheckIPHeader': warning: IP header unaligned, cannot use fast IP checksum (Try passing the configuration throughclick-align'.)
mazu-nat.click:78: While configuring 'extern_dev/from :: FromDevice':
warning: device 'extern:eth' is down
mazu-nat.click:78: While configuring 'intern_dev/from :: FromDevice':
warning: device 'intern:eth' is down
mazu-nat.click:142: While configuring 'CheckIPHeader@20 :: CheckIPHeader':
warning: IP header unaligned, cannot use fast IP checksum
(Try passing the configuration through `click-align'.)
mazu-nat.click:85: While initializing 'intern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'intern:eth' is down
mazu-nat.click:85: While initializing 'extern_dev/ToHostSniffers@7 :: ToHostSniffers':
warning: device 'extern:eth' is down

**Comment by kohler** [comment]
I would not suggest installing mazu-nat.click unless you have modified it to refer to your devices.
Yes, Click is reporting that the Ethernet devices named in the configuration are down.

**Comment by doantungbk** [comment]
Hi Click team,

Thank you for suggesting me! I am sorry for asking some simple questions because I am new in Click Modular Router.  if you do not mind, please explain my following problem to me. I really appreciate your help.
I want to implement NAT on Click Modular Router. But may be I do not understand clearly about mazu-nat. If my GATEWAY is a virtual machine (Linux) running on VirtualBox, what other devices and network interfaces (MODEM, internenal server, internal and external interfaces, and external next hop) should be. I read some papers and find some solution about mazu-nat which runs on VM. But all of them are not clear to me.
I need to run mazu-nat on VM because it is easy to create a backup. My project is related to high availability for middleboxes.
In terms of having something wrong with my idea, please show me a simple example for mazu-nat.

I am so sorry for bothering you!
I wish you guys have a nice day!

**Comment by ahenning** [comment]
Without knowing the end goal I cannot say what all the device you need in the virtual lab, but I can help with the minimal virtual devices to run the NAT routers on VirtualBox.

For example if you have a physical network with a gateway on the LAN then you just need one virtual machine: the NAT router. If there is no physical network, then you would need at a minimum two virtual machines in conjunction with the host machine. The second virtual machine would be a dummy server to test end to end connectivity between the host machine and the server via the NAT router.

Note that VirtualBox virtual networking can be limited and sometimes unpredictable. To break out to the physical network bridge mode is often the way to go and depending on what the VM's need to do on the network layer, promiscuous mode may need to be enabled as well.

Minimal example with physical network and a single interface. Create one click VM, add a single interface that is connected to the physical network. Set bridge mode and just in case promiscuous mode enabled as well. Edit thomer-nat.click to match the network addresses. Remove the kernel mode tohost if you are using userlevel. In this example the host machine and the eth0-in share the same range and eth0-ex share the same IP range as the physical network.

Minimal example with physical network and two interfaces. Same as above but here you can use a host-only network between the host machine and the router VM. The second interface is the physical interface between the VM and the physical network in bridge mode. In this scenario edit mazu-net.click to match the network addresses and userland if required.

Minimal example with only virtual networks: Create two interfaces, use bridge mode or a host-only adapter to communicate between the host and the NAT router VM (internal) and a virtuabox internal network to link to the test server (extern). Then edit mazu-nat.click to match the network address and userland if required.

I would start here before trying anything fancy. You'll have to figure out the addressing scheme, gateways and other omitted details though.

Lastly, IMHO use userland click unless there is a good reason to use kernel mode.

**Comment by doantungbk** [comment]
Dear Ahenning,

Thank you for your detailed explanation!
You showed three choices to me, last one (Minimal example with only virtual networks) is a case which I had intention to implement before. Having a problem that I misunderstand is how to connect beween router VM and physical network. As you know, in real network, physical network connects to hardware router through cable. However, in this case, our router VM runs on VirtualBox which is on host machine. Further, with mazu-nat, it is not clear to me about the connection between NAT router VM and internal network or MODEM. It is only thing that I misunderstand when discussing in this thread.
Your comment makes me confused:
"For example if you have a physical network with a gateway on the LAN then you just need one virtual machine: the NAT router"
As mentioned earlier, my goal is that I need to run mazu-nat on VM because it is easy to create a backup for NAT router VM. My project is related to high availability for middleboxes. Have you heard about some papers such as "Rollback-Recovery for Middlebox" or "Lost in Network Address Translation: Lessons from Scaling the World's Simplest MiddleBox "? All of them are implemented based on Click Modular Router. I have an intention to redeploy them. First of all, I only want to make a simple example with only virtual networks because I misunderstand about connetcion between NAT router VM and physical network. 
if using VM on Virtualbox is not a good idea, would you please show me another way to archieve my goal?

I really appreciate your help.
I wish you have a nice day!

**Comment by ahenning** [comment]
When using only virtual networks (i.e. no physical network), use the VirtualBox "Internal Network" interfaces: Network -> Adapter 2 -> Enable Adapter -> Connect to: Internal Network -> Name: extern. In other words use the VirtualBox "internal networks" to create the virtual networks that you need.

What does MODEM mean? Is it a physical device? If so, how would you connect to it with only virtual networks? To connect to the physical network you need to use a real physical network interface with a network cable or wifi connected to the physical network. In that case "Adapter-X -> Connect to: Bridged Adapter" and select the adapter that is connected to the physical network.

**Comment by doantungbk** [comment]
Hi Ahenning,

Thank you for your quick respone!
I know how to set up virtual networks on VirtualBox. I mean MODEM is a physical device. I ask you for MODEM because  mazu-nat.click file mentioned to MAC address in MODEM (extern_next_hop).

**Comment by ahenning** [comment]
Both posts says to use a bridge adapter to connect to the physical network. But it is still not clear what the MODEM actually is. Is it actually a router on the LAN with IP & MAC addresses or are you trying build a 3G router with click.

**Comment by doantungbk** [comment]
Hi Ahenning,

I am sorry if I say unclearly. I just mention to router on the LAN with IP & MAC addresses.

**Comment by ahenning** [comment]
Yes, connect the virtualbox adapter 2 with bridge mode to the physical network. Adapter 1 can be a host only connection. The host pc has the internal mazu-nat address as gateway and the external side of the nat configuration needs to match the router on the LAN. If the routes are setup correctly, you should be able to communicate with the router on the LAN via the click VM nat router.

i.e: Host-PC-Intern ---1--- Click-VM ---2--- LAN-Router-Extern (Modem)

**Comment by doantungbk** [comment]
Thank you very much. Your explanation brings all information which I really need to do.
Thank you for spending time with me again!
Wish you have a nice day!
