### ISSUE TITLE
CheckIPHeader is error in Linux Module

### ISSUE THREAD

**Issue by PineUnion** [kohler/click#221]
Hi all,
I am new in Click Modular Router. I run Click on 2.6.32-38 Kernel version.
Currently, I have an trouble with Linux Module (running Click under user mode is OK). Whenever I run *.click file under Linux mode, I always get some errors like that:
................................................................................................................
pineclick@pineclick:~/click/conf$ sudo click-install test-ping.click
[sudo] password for pineclick: 
test-ping.click:17: While configuring 'CheckIPHeader@3 :: CheckIPHeader':
  warning: IP header unaligned, cannot use fast IP checksum
  (Try passing the configuration through `click-align'.)
.................................................................................................................
I also searched some solutions for this problem. Someone said that  I need to patch Linux Kernel. Could you please confirm that patched linux kernel is necessary? I also heard about patchless before. If I can use patchless under linux mode, pleaase show me how to install patchless.

I am sorry for asking a simple question!
Thank you very much!

**Comment by kohler** [comment]
This is not a problem. It is only a warning.

if you want to not get the warning, try

`click-align test-ping.click | sudo click-install`

**Comment by PineUnion** [comment]
Thanks. It works now!
