### ISSUE TITLE
Parallel Implementation with DPDK 

### ISSUE THREAD

**Issue by muradkablan** [kohler/click#227]
Hi, 
I am using Click userlevel with DPDK. I created a push element (I call it pushreadblockc) that performs some packet processing. The element is fairly simple and it contains run_task function to check if the processing of the packet is done or not. 

I tried to optimize my router performance by adding a classifier that spread the traffic among running multiple of pushreadblockc elements so they can run in parallel, but the performance became worse and the throughput degraded. 

My questions are:
1- Is my below configuration proper? 
2- Could the run_task function in my pushreadblockc element cause this issue? If so what should I do?
3- I thought of multi-threading, but I don't know how to add -t argument to my running of Click command with all DPDK stuff. And even so, will multi threading help me get a better performance?

This is how I run Click with DPDK:
$ build/bin/click -c 2 --pci-whitelist 0000:82:10.0 --file-prefix pg1  conf/test-multi-nonBlock-dpdk.click

Thanks.
Murad
......................................

fd :: FromDPDKDevice(0);
td :: ToDPDKDevice(0); //Discard;

AddressInfo(
  intern        10.15.0.1       10.15.0.0/24    90:e2:ba:84:4e:a6
);

intern_arp_class :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);

fd -> intern_arp_class;

intern_arp_class[0] -> ARPResponder(intern) -> Discard;    // ARP queries
intern_arp_class[1] -> Discard;
intern_arp_class[3] -> Discard;

intern_arp_class[2] -> Strip(14)
        -> CheckIPHeader
        -> EtherEncap(0x0800, 02:09:c0:b7:a2:de, 90:e2:ba:84:46:20)
        -> port_classifier :: IPClassifier(dst port 1234, dst port 1235, -); 
          port_classifier[0] -> Queue(100000) -> Unqueue -> PushReadBlock -> td;
          port_classifier[1] -> Queue(100000) -> Unqueue -> PushReadBlock -> td;
          port_classifier[2] -> Discard;

**Comment by bcronje** [comment]
I dont quite understand what you are trying to accomplish with PushReadBlock. Can you explain this a bit more? Or ideally post your main element code. So far with the limited information supplied is does not sound like a task is what you need.

I havent experimented with multithreading and FromDPDKDevice yet, but I can tell you to use Click with multithreading you need to either use StaticThreadSched http://read.cs.ucla.edu/click/elements/staticthreadsched or BalancedThreadSched http://read.cs.ucla.edu/click/elements/balancedthreadsched to tell Click which element tasks should be scheduled on which thread.

As an example, change to the following:

    port_classifier[0] -> Queue(100000) -> uq1::Unqueue -> PushReadBlock -> td;
    port_classifier[1] -> Queue(100000) -> uq2::Unqueue -> PushReadBlock -> td;
    StaticThreadSched(fd 0, uq1 1, uq2 2);

This will tell Click to schedule fd on thread 0, uq1 on thread 1 and uq2 on thread 2. And start Click with at least 3 threads.

**Comment by muradkablan** [comment]
I'll post the code when I get to my lab tomorrow. I'm the meanwhile, on what basic you choose the elements to assign them threads? 

Do you choose the ones that run run_task function? Do you have to choose all of them? 

Also, how do you run click with multithreading and DPDK? I tried to use -t argument with my run command above but click didn't accept it with DPDK arguments.

Thanks for your help.

**Comment by bcronje** [comment]
Yes, any element that implements a Click Task, i.e. run_task can be scheduled using the thread schedule elements. If you dont specify it explicitly then it will be scheduled on thread 0.

As I mentioned, I have never tried to run multithreaded Click with DPDK, so I dont know how or if it is possible. Maybe @tbarbette can enlighten us.

**Comment by tbarbette** [comment]
Hi,
To launch Click in DPDK mode with multipe threads (as with any other DPDK application) you've got to allow the application to run on multiple core using the "-c" parameter which specify the core mask. 

Your command allows only to run on the CPU number 1 as you specify -c 2. "-c f" will allow Click to run on the first 4 cores.

Like bcronje said, on top of that you have to assign elements to threads. As it, simply using -c f and assingning elements to different cores, you should already see a gain.

But you can do beter...

Recent NICs (probably all the ones supported by DPDK) allows to split the incomming traffic directly inside the NIC, and give the traffic to multiple hardware queues handled by multiple different independent cores, this is called multiqueue, and the load balancing mechanism RSS (for intel cards).

If you simply use two FromDPDKDevice element, assigned to two different queues like that :

fdA :: FromDPDKDevice(0,0);
fdB :: FromDPDKDevice(0,1);

You'll receive half of the RX traffic in each element without even playing with two ports like you do in port_classifier. The goal being to assign them to two different threads, you should add : 
StaticThreadSched(fdA 0,fdB 1)

In my research I found that in most cases (nearly all), you prefer to use multiqueue to dispatch the traffic to multiple cores, then keep your packet on the same core until you send it through ToDPDKDevice if possible. In practice, do that by also removing the "Queue(100000) -> Unqueue" parts of your configuration. And you'll have to copy fd -> intern_arp_class; for both fdA and fdB. If you run "perf top -ag" you'll find that the Queue->Unqueue part of the pipeline is using a big part of the CPU, this scheme allows to avoid cache misses but also to avoid that scheduling cost and the heavy, atomic, notifications between queue and unqueue.

Be sure in this case that PushReadBlock is thread safe. If it's not, simply duplicate the whole path per-thread.

**Comment by muradkablan** [comment]
Thank you guys for your feedback. 
@tbarbette , I tried your suggestion but I got the following error:
conf/test-multi-thread-dpdk.click:3: While initializing 'td :: ToDPDKDevice':
Cannot initialize DPDK port 0 with 3 RX and 1 TX queues
Router could not be initialized!

This is how I run Click:
build/bin/click -c f --pci-whitelist 0000:82:10.0 --file-prefix pg1 --socket-mem 2048,2048 conf/test-multi-thread-dpdk.click 

and this is my click file:
fdA :: FromDPDKDevice(0,0);
fdB :: FromDPDKDevice(0,1);
td :: ToDPDKDevice(0);

StaticThreadSched(fdA 0,fdB 1)

AddressInfo(
  intern        10.15.0.1       10.15.0.0/24    90:e2:ba:84:4e:a6
);

intern_arp_classA :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);
intern_arp_classB :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);

fdA -> intern_arp_classA;
fdB -> intern_arp_classB;

intern_arp_classA[0] -> ARPResponder(intern)     // ARP queries
        -> Discard;
intern_arp_classA[1] -> Discard;
intern_arp_classA[3] -> Discard;

intern_arp_classA[2] -> Strip(14) -> CheckIPHeader(CHECKSUM false) -> EtherEncap(0x0800, 02:09:c0:b7:a2:de, 90:e2:ba:84:46:20)
          -> PushReadSync() -> td;


intern_arp_classB[0] -> ARPResponder(intern)     // ARP queries
        -> Discard;
intern_arp_classB[1] -> Discard;
intern_arp_classB[3] -> Discard;

intern_arp_classB[2] -> Strip(14) -> CheckIPHeader(CHECKSUM false) -> EtherEncap(0x0800, 02:09:c0:b7:a2:de, 90:e2:ba:84:46:20)
          -> PushReadSync() -> td;

**Comment by tbarbette** [comment]
What is your Network card?

**Comment by muradkablan** [comment]
The machine has 82599ES 10-Gigabit SFI/SFP+ Network Connection

The NIC I'm using with Click is VF:
0000:82:10.0 '82599 Ethernet Controller Virtual Function' drv=igb_uio

**Comment by muradkablan** [comment]
Hi,
Any feedback is appreciated.

**Comment by tbarbette** [comment]
Hi,
I still have to try your configuration. The error suggest that there is at least a problem in the accounting of queues, it should 2 RX and 1 TX queue, not 3RX and 1 TX. I doubt it's the final problem but it is not normal.
I never tried DPDK with VF driver. Can you try with the normal driver under a non-virtualized environment? To rule out the problem...
Thanks,
Tom

**Comment by tbarbette** [comment]
I just added a PR to solve a problem in the assignment of queues, as DPDK should try to allocate 2 RX queues and 1 TX queues in your case and not 3/1. Can you try with that version?

For me, with the non-vf 82599-based NIC it works. If it doesn't, could you put a ToDPDKDevice(0,1) somewhere to force having the same amount of RX and TX queues?

If it doesn't, I'll try the VF driver. If you can explain your setup, I would gain some time...
Sorry for the delay, BTW...

**Comment by tbarbette** [comment]
The assignment fix has been merged. Can you give us an update @muradkablan ? Thanks

**Comment by muradkablan** [comment]
Hi Tom, 
Thanks for the update.
I tested the above click setup with your update and it seems to work and I no longer see the errors.
I also tested with VF driver and it works as well.

I didn't test the performance/overhead of such setup though. I will not able to do this for the next month as I have to focus on another project that doesn't involve Click. 

Thanks again,
