### ISSUE TITLE
Click DPDK with Mellanox NIC

### ISSUE THREAD

**Issue by yiannisy** [kohler/click#229]
Hi,

I am experimenting with Click and DPDK with a Mellanox Connect 3 10G card (using the mlx4 driver), but can't get it to work. 

I try the following configuration, but I am getting a "Router could not be initialized error".
FastUDPSource(500000, 10000000, 70, 1:2:3:4:5:6, 2.0.0.2, 1234,e4:1d:2d:6d:5b:d0, 2.0.0.1, 1234, 1, 0, 1) -> ToDPDKDevice(0000:0b:00.0);

I also tried ToDPDKDevice(0) and ToDPDKDevice(eth2) instead of 0000:0b:00.0 but no luck.
- Does the configuration make sense or should I use ToDPDKDevice differently?
- Is there any way to enable more verbose output besides the cryptic Router could not be initialized message?

I am novice with both DPDK and Click and might be missing something obvious. 
However, I was able to use DPDK's pktgen and got 10G usage.

More setup details follow..

[1]  dpdk_nic_bind --status
Network devices using DPDK-compatible driver
# 

<none>

Network devices using kernel driver
# 

0000:04:00.0 'NetXtreme II BCM5708 Gigabit Ethernet' if=eth0 drv=bnx2 unused=igb_uio _Active_

0000:08:00.0 'NetXtreme II BCM5708 Gigabit Ethernet' if=eth1 drv=bnx2 unused=igb_uio 

0000:0b:00.0 'MT27500 Family [ConnectX-3]' if=eth2,eth4 drv=mlx4_core unused=igb_uio 

Other network devices
# 

<none>

[2] exact command : 

sudo click -c 0xf -n 1 -- yy/udptest.click

EAL: Detected lcore 0 as core 0 on socket 0

EAL: Detected lcore 1 as core 0 on socket 0

EAL: Detected lcore 2 as core 2 on socket 0

EAL: Detected lcore 3 as core 2 on socket 0

EAL: Detected lcore 4 as core 1 on socket 0

EAL: Detected lcore 5 as core 1 on socket 0

EAL: Detected lcore 6 as core 3 on socket 0

EAL: Detected lcore 7 as core 3 on socket 0

EAL: Support maximum 128 logical core(s) by configuration.

EAL: Detected 8 lcore(s)

EAL: VFIO modules not all loaded, skip VFIO support...

EAL: Setting up physically contiguous memory...

EAL: Ask a virtual area of 0x1c800000 bytes

EAL: Virtual area found at 0x7f4dbda00000 (size = 0x1c800000)

EAL: Ask a virtual area of 0xe400000 bytes

EAL: Virtual area found at 0x7f4daf400000 (size = 0xe400000)

EAL: Ask a virtual area of 0xe400000 bytes

EAL: Virtual area found at 0x7f4da0e00000 (size = 0xe400000)

EAL: Ask a virtual area of 0x200000 bytes

EAL: Virtual area found at 0x7f4da0a00000 (size = 0x200000)

EAL: Ask a virtual area of 0x63400000 bytes

EAL: Virtual area found at 0x7f4d3d400000 (size = 0x63400000)

EAL: Ask a virtual area of 0x200000 bytes

EAL: Virtual area found at 0x7f4d3d000000 (size = 0x200000)

EAL: Ask a virtual area of 0x31c00000 bytes

EAL: Virtual area found at 0x7f4d0b200000 (size = 0x31c00000)

EAL: Ask a virtual area of 0x200000 bytes

EAL: Virtual area found at 0x7f4d0ae00000 (size = 0x200000)

EAL: Ask a virtual area of 0x31800000 bytes

EAL: Virtual area found at 0x7f4cd9400000 (size = 0x31800000)

EAL: Ask a virtual area of 0x200000 bytes

EAL: Virtual area found at 0x7f4cd9000000 (size = 0x200000)

EAL: Requesting 2048 pages of size 2MB from socket 0

EAL: TSC frequency is ~2327521 KHz

EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !

EAL: Master lcore 0 is ready (tid=dcf13940;cpuset=[0])

EAL: lcore 3 is ready (tid=d7ffd700;cpuset=[3])

EAL: lcore 2 is ready (tid=d87fe700;cpuset=[2])

EAL: lcore 1 is ready (tid=d8fff700;cpuset=[1])

‘FastUDPSource@1 :: FastUDPSource’ pull output 0 connected to ‘ToDPDKDevice@2 :: ToDPDKDevice’ push input 0

Router could not be initialized!

Thanks,
Yiannis

**Comment by tbarbette** [comment]
Hi,

The parameter of ToDPDKDevice is the number of the port (this is assigned by DPDK, in DPDK interface work by ports, not name like eth2). Should be ToDPDKDevice(0) in your case.

The problem here is written at the before-last line of your log. FastUDPSource is a "pull" element, and todpdkdevice a "push" element. Insert a pull-to-push element between, or use InfiniteSource for example ;)

Good luck !

Tom

**Comment by yiannisy** [comment]
Thanks for the prompt reply Tom.

Replacing with InfiniteSource helped. The error that I get now is that it
cannot find any DPDK-enabled port.

yy/fastudpsrc.click:3: While initializing ‘ToDPDKDevice@2 :: ToDPDKDevice’:
 No DPDK-enabled ethernet port found
Router could not be initialized!

Connect3X works with the mlx4 driver, not sure if this causes
rte_dev_eth_count() to return 0.
I was able to use DPDK on eth2 using port 0 as index..

Any ideas what could cause this?
Thanks,
Yiannis




On Sat, Jan 16, 2016 at 10:57 AM, Tom Barbette <notifications@github.com>
wrote:

> Hi,
>
> The parameter of ToDPDKDevice is the number of the port (this is assigned
> by DPDK, in DPDK interface work by ports, not name like eth2). Should be
> ToDPDKDevice(0) in your case.
>
> The problem here is written at the before-last line of your log.
> FastUDPSource is a "pull" element, and todpdkdevice a "push" element.
> Insert a pull-to-push element between, or use InfiniteSource for example ;)
>
> Good luck !
>
> Tom
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohler/click/issues/229#issuecomment-172246444>.
>



-- 
Yiannis .

**Comment by tbarbette** [comment]
Your "dpdk_nic_bind --status" output suggests that the NICs are not in DPDK mode.  use dpdk_nic_bind.py --bind=uio_pci_generic 0000:04:00.0 to bind your driver (or igb_uio, or whatever).

**Comment by yiannisy** [comment]
So my NIC is Mellanox. My understanding is that Mellanox cards need to be
binded with mlx4 driver, not with uio_pci_generic or igb_uio.

When I try bind with uio_pci_generic I get the following error: Error: bind
failed for 0000:0b:00.0 - Cannot open
/sys/bus/pci/drivers/uio_pci_generic/bind

I can bind with igb_uio but click gives me the same error, and also I
cannot the interface is not listed with ifconfig -a.

Also, I was able to use DPDK's pktgen with mlx4, which means that this
binding should be good enough for DPDK...


On Sun, Jan 17, 2016 at 2:26 AM, Tom Barbette <notifications@github.com>
wrote:

> Your "dpdk_nic_bind --status" output suggests that the NICs are not in
> DPDK mode. use dpdk_nic_bind.py --bind=uio_pci_generic 0000:04:00.0 to bind
> your driver (or igb_uio, or whatever).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kohler/click/issues/229#issuecomment-172310264>.
>



-- 
Yiannis .

**Comment by yiannisy** [comment]
Hi Tom,
For Mellanox and mlx4 support I had to add the necessary library in userlevel/dpdk.mk :

 LIBS += -lrte_pmd_pcap -lpcap
 endif
 
+ifeq ($(CONFIG_RTE_LIBRTE_MLX4_PMD),y)
+LIBS += -libverbs -lrte_pmd_mlx4
+endif
+
 endif # Plugins

I then got a "Cannot allocation Mbufs" error and had to decrease the NB_MBUF from dpdkdevice.cc. 
The error I get now is:
"Cannot initialize DPDK port 0 with 0 RX and 1 TX queues"

Thanks,
Y.

**Comment by tbarbette** [comment]
Both error are fixed in https://github.com/tbarbette/click/tree/PRClickSecondaryProcess in fact... I'm waiting for @kohler to accept some PR before sending that new one.

You can change NR_MBUF by using DPDKInfo(X) where X is the number of mbuf.

**Comment by tbarbette** [comment]
Can you try with that version and report back? Thanks !

**Comment by yiannisy** [comment]
Hi Tom,
Just tried the branch you suggested and seems to work fine so far - thans! 
I had one issue only while building. 
When I compile it fails to link because it cannot find libverbs symbols. I had to manually add -libverbs next to lrte_pmd_mlx4 ( not sure why the earlier libverbs statement is not enough ).

**Comment by yiannisy** [comment]
Tom,
Following-up on the previous, and to make sure I don't miss something in terms of performance. 

- Using pktgen I can get close to 10Gbps for max packet sizes, but drops down to 2Gbps for 64 bytes.
- Using Click to generate traffic (InfiniteSource -> ToDPDKDevice) is 40% - 50% slower. Is this performance drop expected or can this be related with my config parameters?

You can find a graph here : http://tinyurl.com/zojzbl6
Machine specs : Intel(R) Xeon(R) CPU, E5345  @ 2.33GHz, and 16GB of RAM.

Thanks,
Y.

**Comment by tbarbette** [comment]
First, add the argument "TIMEOUT -1" to your ToDPDKDevice, TIMEOUT is not needed for a pkt-gen type application.
Also, the actual version of Click does not support batching, a lot of your CPU time is lost trying to resolve virtual functions calls for each packets. And because it does not know if the packet is received is part of a burst or the end of a packet burst, it plays with timer (disabled with timeout -1). I never used it but click-devirtualizer tool may help you for the virtual call, which can really be a big hit in this kind of configuration. Try to fidn the bootleneck with "perf top -a -g".
Regardint those problems, we have a batching-enabled version of Click here : https://github.com/tbarbette/fastclick .
I would like to see the result of perf after disabling the timer ;)

**Comment by tbarbette** [comment]
Any news on this?

**Comment by yiannisy** [comment]
Hi,

Sorry for the late reply - I ended up switching to an Intel-based setup as it seemed more robust and also had better support for MoonGen (which I ended up using). 

I tried TIMEOUT -1 with Mellanox again today, but didn't see any significant difference. Interleaving between no timeout option and timeout=-1 gives a ~10% increase with the latter. But still, the numbers are similar to what I've seen with the Click Traffic generator earlier...

Y.

**Comment by tbarbette** [comment]
You may have reached the limit of mainline Click, can you give the result of "perf top -a -g" to check that fact or see if there's a problem somewhere ?
You can try FastClick, you shouldn't have to change anything in the config. If you're doing a performance study, I'd be interested if you try it. But yes if your goal is only to generate packets, MoonGen seems great.

**Comment by francisleely** [comment]
Hi, 
I face the problem with the Mellanox MT27520 card. When I try to bind the card with igb_uio driver, it succeed:

[root@localhost dpdk-16.04]# python tools/dpdk_nic_bind.py --status

Network devices using DPDK-compatible driver
============================================
0000:85:00.0 'MT27500 Family [ConnectX-3]' drv=igb_uio unused=

Network devices using kernel driver
===================================
0000:03:00.0 'I350 Gigabit Network Connection' if=enp3s0f0 drv=igb unused=igb_uio *Active*
0000:07:00.0 '82576 Gigabit Network Connection' if=enp7s0f0 drv=igb unused=igb_uio 
0000:07:00.1 '82576 Gigabit Network Connection' if=enp7s0f1 drv=igb unused=igb_uio 
0000:0b:00.0 '82574L Gigabit Network Connection' if=enp11s0 drv=e1000e unused=igb_uio 
 
While when I try to run kni example, it shows me that No Supported Ethernet Devices found. What is the probelm? Should I change some config thing? By the way, I do not find .config file in the dpdk-16.04 folder to change the parameters, how can I do? Thanks a lot.

..........
APP: Port ID: 0
APP: Rx lcore ID: 1, Tx lcore ID: 2
EAL: Error - exiting with code: 1
  Cause: No supported Ethernet device found

**Comment by tbarbette** [comment]
Use tools/setup.py to generate a configuration for x86_64-native-linuxapp-gcc, it will create a folder of that name in the dpdk folder which contains .config. You can also edit config/common_linuxapp. I also suggest to start with something else than KNI. Testpmd for example. KNI requires another module and is another story...

Moreover Click is not currently compatible with 16.04, I've got a patch coming in, meanwhile you will probably want to use 2.2.0.
