### ISSUE TITLE
Compiling with c++11

### ISSUE THREAD

**Issue by muradkablan** [kohler/click#230]
Hi,
I need to link a package that requires c++11 with Click. I would like to include the header files directly. 
Is there anyway to compile Click with g++4.9 using c++11 extension?

Thanks,

**Comment by tbarbette** [comment]
Just add CXXFLAGS="-std=gnu++11" in your ./configure arguments ;)

**Comment by muradkablan** [comment]
It gave me the below error. BTW, I'm also using DPDK if that makes a different. multiread.hh is where I link the library from the other package.


/click# make V=1 install             
make[1]: Entering directory `/stateless-mb-code-and-exp-setup/click/userlevel'
g++   -DHAVE_CONFIG_H -I../include -I../include -I. -I..   -std=gnu++11 -I/usr/local/include/ramcloud  -m64 -pthread  -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_AES -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_AVX -DRTE_MACHINE_CPUFLAG_RDRAND -DRTE_MACHINE_CPUFLAG_FSGSBASE -DRTE_MACHINE_CPUFLAG_F16C -DRTE_MACHINE_CPUFLAG_AVX2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2,RTE_CPUFLAG_AES,RTE_CPUFLAG_PCLMULQDQ,RTE_CPUFLAG_AVX,RTE_CPUFLAG_RDRAND,RTE_CPUFLAG_FSGSBASE,RTE_CPUFLAG_F16C,RTE_CPUFLAG_AVX2  -I/stateless-mb-code-and-exp-setup/click/userlevel/build/include -I/dpdk/x86_64-native-linuxapp-gcc/include -include /dpdk/x86_64-native-linuxapp-gcc/include/rte_config.h  -MD -MP -c ../elements/standard/multiread.cc -o multiread.o
In file included from ../elements/standard/multiread.cc:5:0:
../include/click/args.hh: In member function 'bool IntArg::parse_saturating(const String&, V&, const ArgContext&)':
../include/click/args.hh:1064:19: error: expected nested-name-specifier before 'make_unsigned'
  typedef typename make_unsigned<V>::type unsigned_v_type;
                   ^
../include/click/args.hh:1064:32: error: expected initializer before '<' token
  typedef typename make_unsigned<V>::type unsigned_v_type;
                                ^
../include/click/args.hh:1065:38: error: 'unsigned_v_type' does not name a type
  extract_integer(x, reinterpret_cast<unsigned_v_type &>(result));
                                      ^
../include/click/args.hh:1065:54: error: expected '>' before '&' token
  extract_integer(x, reinterpret_cast<unsigned_v_type &>(result));
                                                      ^
../include/click/args.hh:1065:54: error: expected '(' before '&' token
../include/click/args.hh:1065:55: error: expected primary-expression before '>' token
  extract_integer(x, reinterpret_cast<unsigned_v_type &>(result));
                                                       ^
make[1]: *** [multiread.o] Error 1
make[1]: Leaving directory `/stateless-mb-code-and-exp-setup/click/userlevel'
make: *** [install-userlevel] Error 2

**Comment by muradkablan** [comment]
Ok, I figured out the cause of the problem but still no solution. As I thought, DPDK package is conflicting with the new package I want to link Click with.

If I don't enable dpdk with config, I can link Click to the other package using CXXFLAGS="-std=gnu++11".
When I enable DPDK, I get the this error.

make[1]: Entering directory `/stateless-mb-code-and-exp-setup/click/userlevel'
g++   -DHAVE_CONFIG_H -I../include -I../include -I. -I..   -std=c++11 -I/usr/local/include/ramcloud  -m64 -pthread  -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_AES -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_AVX -DRTE_MACHINE_CPUFLAG_RDRAND -DRTE_MACHINE_CPUFLAG_FSGSBASE -DRTE_MACHINE_CPUFLAG_F16C -DRTE_MACHINE_CPUFLAG_AVX2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2,RTE_CPUFLAG_AES,RTE_CPUFLAG_PCLMULQDQ,RTE_CPUFLAG_AVX,RTE_CPUFLAG_RDRAND,RTE_CPUFLAG_FSGSBASE,RTE_CPUFLAG_F16C,RTE_CPUFLAG_AVX2  -I/stateless-mb-code-and-exp-setup/click/userlevel/build/include -I/dpdk/x86_64-native-linuxapp-gcc/include -include /dpdk/x86_64-native-linuxapp-gcc/include/rte_config.h  -MD -MP -c ../elements/userlevel/fromdpdkdevice.cc -o fromdpdkdevice.o
In file included from /dpdk/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:182:0,
                 from ../elements/userlevel/fromdpdkdevice.cc:26:
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h: In function 'int eal_parse_pci_BDF(const char*, rte_pci_addr*)':
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:20: error: 'typeof' was not declared in this scope
  (fd) = (typeof (fd))val;                                \
                    ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:283:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->bus, UINT8_MAX, ':');
  ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:22: error: expected ';' before 'val'
  (fd) = (typeof (fd))val;                                \
                      ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:283:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->bus, UINT8_MAX, ':');
  ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:20: error: 'typeof' was not declared in this scope
  (fd) = (typeof (fd))val;                                \
                    ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:284:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->devid, UINT8_MAX, '.');
  ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:22: error: expected ';' before 'val'
  (fd) = (typeof (fd))val;                                \
                      ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:284:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->devid, UINT8_MAX, '.');
  ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:20: error: 'typeof' was not declared in this scope
  (fd) = (typeof (fd))val;                                \
                    ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:285:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->function, UINT8_MAX, 0);
  ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:22: error: expected ';' before 'val'
  (fd) = (typeof (fd))val;                                \
                      ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:285:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->function, UINT8_MAX, 0);
  ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h: In function 'int eal_parse_pci_DomBDF(const char*, rte_pci_addr*)':
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:262:20: error: 'typeof' was not declared in this scope
  (fd) = (typeof (fd))val;                                \
                    ^
/dpdk/x86_64-native-linuxapp-gcc/include/rte_pci.h:304:2: note: in expansion of macro 'GET_PCIADDR_FIELD'
  GET_PCIADDR_FIELD(input, dev_addr->domain, UINT16_MAX, ':');
  ^

**Comment by bcronje** [comment]
@kohler did mention in a previous issue that Click is close to being compatible with c++11. But I do not think any work into that has taken place since then.

**Comment by muradkablan** [comment]
Thanks, 
I think I might solved the issue. Instead of c++11, I used  CXXFLAGS=-std=gnu++11
It compiles and links fine. 
I will write some code and see if it runs without any issues.

**Comment by tbarbette** [comment]
I nearly always compile click with -std=gnu++11 due to some of my elements and it works very well ;)
