### ISSUE TITLE
Why is Vector<int> tree not a private member of Program in elements/standard/classification.hh ?

### ISSUE THREAD

**Issue by glemin** [kohler/click#238]
Hello,

I am currently working on a Classifier that accepts ip6 and I was wondering why the tree argument is passed so many times as an argument in the Program class in elements/standard/classification.hh and ([click here to see where the Program class got declared in elements/standard/classification.hh](https://github.com/kohler/click/blob/master/elements/standard/classification.hh#L144)). At the bottom I have also added (I hope) a complete list of the Program methods that pass tree\<int\>& as an argument.

Isn't it better, from a software engineering point of view, to decrease coupling and increase cohesion by adding the tree method as a private  of Program in stead of passing it the whole time over the place? Or does tree really have some sort of specific meaning I am not aware of and does it as such need to be passed as an argument?

Also as discussed in the more broader topic on this #240  , it might even be possible to refactor the Program class so that it contains a ParseTree member in it (with ParseTree on its own having Vector\<int\>& tree as a member in it), which has the functions add_insn(...), finish_subtree(...), negate_subtree(...) in it, and possibly Program can then even be constructed with this ParseTree class, after the ParseTree class walked walked from Primitive to Primitive and each primitive having add their part to the ParseTree in it.

Below the lists of all methods that pass tree as an argument (if I did not forget one):

```
void
Program::start_subtree(Vector<int> &tree) const
{
  ++tree[0];
}

void
Program::add_insn(Vector<int> &tree, int offset, uint32_t value, uint32_t mask)
{
  _insn.push_back(Insn(offset, value, mask));
  tree.push_back(tree[0]);
  _output_everything = -1;
}


void
Program::finish_subtree(Vector<int> &tree, Combiner combiner,
int success, int failure)
{
  int level = tree[0];
  // 'subtrees' contains pointers to trees at level 'level'
  Vector<int> subtrees;
  {
    // move backward to parent subtree
    int ptr = _insn.size();
    while (ptr > 0 && (tree[ptr] < 0 || tree[ptr] >= level))
      --ptr;
    // collect child subtrees
    for (++ptr; ptr <= _insn.size(); ++ptr)
      if (tree[ptr] == level)
        subtrees.push_back(ptr - 1);
      }
    if (subtrees.size()) {
      // combine subtrees
      // first mark all subtrees as next higher level
      tree[subtrees[0] + 1] = level - 1;
      for (int e = subtrees[0] + 2; e <= _insn.size(); e++)
        tree[e] = -1;
      // loop over expressions
      int t;
      for (t = 0; t < subtrees.size() - 1; t++) {
        int first = subtrees[t];
        int next = subtrees[t+1];
        if (combiner == c_and)
          redirect_subtree(first, next, next, failure);
        else if (combiner == c_or)
          redirect_subtree(first, next, success, next);
        else if (combiner == c_ternary) {
          if (t < subtrees.size() - 2) {
            int next2 = subtrees[t+2];
          redirect_subtree(first, next, next, next2);
          redirect_subtree(next, next2, success, failure);
          t++;
          } else	// like c_and
            redirect_subtree(first, next, next, failure);
        } else
          redirect_subtree(first, next, success, failure);
      }
      if (t < subtrees.size()) {
        assert(t == subtrees.size() - 1);
      redirect_subtree(subtrees[t], _insn.size(), success, failure);
    }
  }
  --tree[0];
}

void
Program::negate_subtree(Vector<int> &tree, bool flip_short)
{
  // swap 'j_success' and 'j_failure' within the last subtree
  int level = tree[0];
  int first = _insn.size() - 1;
  while (first >= 0 && tree[first+1] != level)
    --first;
  for (int i = first; i >= 0 && i < _insn.size(); i++) {
    Insn &e = _insn[i];
    if (e.yes() == j_failure)
      e.yes() = j_success;
    else if (e.yes() == j_success)
      e.yes() = j_failure;
    if (e.no() == j_failure)
      e.no() = j_success;
    else if (e.no() == j_success)
      e.no() = j_failure;
    if (flip_short)
      e.short_output = !e.short_output;
  }
}
```

Best Regards,
Glenn

**Comment by kohler** [comment]
Thank you for your opinions about software engineering.

The IPFilter/IPClassifier classes are some of Click's hidden gems. They have been extensively engineered for performance—we found good performance critical in some of our applications at Mazu Networks and at Meraki—and contain some seriously interesting algorithms for classifier tree optimization. They essentially implement BPF, but in some cases better than BPF does.

I won't engage on abstract issues of software engineering taste. Questions like “Isn't it better, from a software engineering point of view” are not interesting. If you have a pull request, I will consider it. But be warned that I take a very dim view of pull requests that merely change working code to supposedly make them better engineered. Such pull requests frequently introduce bugs and are rarely worth it.

For what it's worth, `tree` is an argument and not a member because it is not needed once the program has been constructed. It would make more sense to the casual reader if `tree` was in a structure such as:

```
struct ProgramCompileState {
   Vector<int> tree;
};
```

and the `Program` methods called during program compilation took a `ProgramCompileState&` argument. Or this might make more sense to the casual reader:

```
struct ProgramCompileState {
   Program* output_program_;
   Vector<int> tree_;
   void negate_subtree(....); // all compilation-type methods go here
};
```

But really who cares?

**Comment by glemin** [comment]
Ah so it is not a member solely out of performance reasons. Wow... you have just blown my mind.

I have never thought about it that way. Mostly here we solely focus on software engineering/software reengineering. I think if performance was an issue we were always using pointers. 

So in stead of making Vector<int> tree our member, we used Vector<int>* tree, so we can free the memory when it is not needed anymore (and have the memory being active for as long as the class lives).

So basically like this,

Vector<int>* tree;

Then you can create him with new, and release him with delete.

Vector<int>* tree = new Vector<int>();

and then you can release the memory again with.

delete tree;

I am not sure whether the object still somehow needs to keep a space in its class to solely hold to pointer to the dynamically allocated address. If that is the case, your solution might be slightly more efficient.

Have you thought about that solution of using dynamic memory allocation and storing the information on the heap in stead of on the stack? I am curious to here about it.

It might indeed be that by using the pointer field, he still needs to keep track of the size of a pointer. Because after a delete, he might still assume that an other new might come somehow. Also I am not sure whether it would be technically possible to implement a "delete_forever" function (which basically frees the space the pointer took in the class). If that would be possible, I really want that compiler function!
