### ISSUE TITLE
Changes in ip6.h

### ISSUE THREAD

**Issue by glemin** [kohler/click#245]
I want to propose a change for ip6.h but before I send a commit I would like to hear what the others think of it.

The file looks now as follows:

```
/* -*- mode: c; c-basic-offset: 4 -*- */
#ifndef CLICKNET_IP6_H
#define CLICKNET_IP6_H
//#include <clicknet/ip.h>
/* get struct in6_addr */
#include <click/cxxprotect.h>
CLICK_CXX_PROTECT
#if CLICK_LINUXMODULE
# include <net/checksum.h>
# include <linux/in6.h>
#else
# include <sys/types.h>
# include <netinet/in.h>
#endif

struct click_ip6 {
    union {
	struct {
	    uint32_t ip6_un1_flow;	/* 0-3	 bits 0-3: version == 6	     */
					/*	 bits 4-11: traffic class    */
					/*	   bits 4-9: DSCP	     */
					/*	   bits 10-11: ECN	     */
					/*	 bits 12-31: flow label	     */
	    uint16_t ip6_un1_plen;	/* 4-5	 payload length		     */
	    uint8_t ip6_un1_nxt;	/* 6	 next header		     */
	    uint8_t ip6_un1_hlim;	/* 7	 hop limit		     */
	} ip6_un1;
	uint8_t ip6_un2_vfc;		/* 0	 bits 0-3: version == 6	     */
					/*	 bits 4-7: top 4 class bits  */
	struct {
#if CLICK_BYTE_ORDER == CLICK_BIG_ENDIAN
	    unsigned ip6_un3_v : 4;	/* 0	 version == 6		     */
	    unsigned ip6_un3_fc : 4;	/*	 header length		     */
#elif CLICK_BYTE_ORDER == CLICK_LITTLE_ENDIAN
	    unsigned ip6_un3_fc : 4;	/* 0	 header length		     */
	    unsigned ip6_un3_v : 4;	/*	 version == 6		     */
#endif
	} ip6_un3;
    } ip6_ctlun;
    struct in6_addr ip6_src;	/* 8-23	 source address */
    struct in6_addr ip6_dst;	/* 24-39 dest address */
};

#define ip6_v			ip6_ctlun.ip6_un3.ip6_un3_v
#define ip6_vfc			ip6_ctlun.ip6_un2_vfc
#define ip6_flow		ip6_ctlun.ip6_un1.ip6_un1_flow
#define ip6_plen		ip6_ctlun.ip6_un1.ip6_un1_plen
#define ip6_nxt			ip6_ctlun.ip6_un1.ip6_un1_nxt
#define ip6_hlim		ip6_ctlun.ip6_un1.ip6_un1_hlim

#define IP6_FLOW_MASK		0x000FFFFFU
#define IP6_FLOW_SHIFT		0
#define IP6_CLASS_MASK		0x0FF00000U
#define IP6_CLASS_SHIFT		20
#define IP6_DSCP_MASK		0x0FC00000U
#define IP6_DSCP_SHIFT		22
#define IP6_V_MASK		0xF0000000U
#define IP6_V_SHIFT		28

#define IP6_CHECK_V(hdr)	(((hdr).ip6_vfc & htonl(IP6_V_MASK)) == htonl(6 << IP6_V_SHIFT))

#ifndef IP6PROTO_FRAGMENT
#define IP6PROTO_FRAGMENT 0x2c
#endif
struct click_ip6_fragment {
    uint8_t ip6_frag_nxt;
    uint8_t ip6_frag_reserved;
    uint16_t ip6_frag_offset;
#define IP6_MF		0x0001
#define IP6_OFFMASK	0xFFF8
					/*	 bits 0-12: Fragment offset  */
					/*	 bit 13-14: reserved	     */
					/*	 bit 15: More Fragment	     */
    uint32_t ip6_frag_id;
};


uint16_t in6_fast_cksum(const struct in6_addr *saddr,
			const struct in6_addr *daddr,
			uint16_t len,
			uint8_t proto,
			uint16_t ori_csum,
			const unsigned char *addr,
			uint16_t len2);

uint16_t in6_cksum(const struct in6_addr *saddr,
		   const struct in6_addr *daddr,
		   uint16_t len,
		   uint8_t proto,
		   uint16_t ori_csum,
		   unsigned char *addr,
		   uint16_t len2);

CLICK_CXX_UNPROTECT
#include <click/cxxunprotect.h>
#endif
```

I don't like the use of the macros ip6_v, ip6_vfc, ip6_flow, ip6_plen, ip6_nxt and ip6_hlim. They have all small letters and it confuses people to think that this are the actual fields, while in fact we have a union. Also macros with small letters is something I don't really like as well.

I don't know where the ip6_un3 is for, so I for now left it out. Some stuff is done with CLICK_BYTE_ORDER == CLICK_BIG_ENDIAN and CLICK_BYTE_ORDER == CLICK_LITTLE_ENDIAN, but I don't see why we should be worried about the endianess (isn't this a compilers job? not sure, but I can be wrong), and I don't see it used in the other unions that are most oftenly used, so I lefted it out in my proposal.

Also there is a CLICK_PROTECT and CLICK_UNPROTECT I somtimes see in code, as in this part of code. But I don't see it in all parts of code. If someone could explain me where this macro is used for, I will write its explanation as well in the macro manual I am going to write.

What I propose is change the code as follows,

```
/* -*- mode: c; c-basic-offset: 4 -*- */
#ifndef CLICKNET_IP6_H
#define CLICKNET_IP6_H
//#include <clicknet/ip.h>
/* get struct in6_addr */
#include <click/cxxprotect.h>
CLICK_CXX_PROTECT
#if CLICK_LINUXMODULE
# include <net/checksum.h>
# include <linux/in6.h>
#else
# include <sys/types.h>
# include <netinet/in.h>
#endif

struct click_ip6 {
    union {
	struct {
	    uint32_t flow;	/* 0-3	 bits 0-3: version == 6	     */
					/*	 bits 4-11: traffic class    */
					/*	   bits 4-9: DSCP	     */
					/*	   bits 10-11: ECN	     */
					/*	 bits 12-31: flow label	     */
	    uint16_t plen;	/* 4-5	 payload length		     */
	    uint8_t nxt;	/* 6	 next header		     */
	    uint8_t hlim;	/* 7	 hop limit		     */
	} format1;

        struct {		
           uint8_t byte0;       /* 0-3	 version == 6	   		   */
					/* 4-7	 differentiated service (part 1)   */
					/*           4-7: DSCP (part 1) 	   */

           uint8_t byte1;       /* 8-11  differentiated service (part 2) */
					/*	     8-9: DSCP (part 2)          */
                                        /*           10-11: ECN                  */
                                        /* 12-15 flow label (part 1)           */
           uint8_t byte2;       /* 16-23 flow label (part 2)           */
           uint8_t byte3;       /* 24-31 flow label (part 3)           */
           uint16_t plen;      /* plen is on bytes 4 and 5 */
	   uint8_t nxt;          /* nxt is on byte 6 */
           uint8_t hlim;        /* hlim is on byte 7 */
        } format2;
    } format_union;

    struct in6_addr src_address;	/* 8-23	 source address */
    struct in6_addr dst_address;	/* 24-39 dest address */
};
#define IP6_FLOW_MASK		0x000FFFFFU
#define IP6_FLOW_SHIFT		0
#define IP6_CLASS_MASK		0x0FF00000U
#define IP6_CLASS_SHIFT		20
#define IP6_DSCP_MASK		0x0FC00000U
#define IP6_DSCP_SHIFT		22
#define IP6_V_MASK		0xF0000000U
#define IP6_V_SHIFT		28

#define IP6_CHECK_V(hdr)	(((hdr).ip6_vfc & htonl(IP6_V_MASK)) == htonl(6 << IP6_V_SHIFT))

#ifndef IP6PROTO_FRAGMENT
#define IP6PROTO_FRAGMENT 0x2c
#endif
struct click_ip6_fragment {
    uint8_t ip6_frag_nxt;
    uint8_t ip6_frag_reserved;
    uint16_t ip6_frag_offset;
#define IP6_MF		0x0001
#define IP6_OFFMASK	0xFFF8
					/*	 bits 0-12: Fragment offset  */
					/*	 bit 13-14: reserved	     */
					/*	 bit 15: More Fragment	     */
    uint32_t ip6_frag_id;
};


uint16_t in6_fast_cksum(const struct in6_addr *saddr,
			const struct in6_addr *daddr,
			uint16_t len,
			uint8_t proto,
			uint16_t ori_csum,
			const unsigned char *addr,
			uint16_t len2);

uint16_t in6_cksum(const struct in6_addr *saddr,
		   const struct in6_addr *daddr,
		   uint16_t len,
		   uint8_t proto,
		   uint16_t ori_csum,
		   unsigned char *addr,
		   uint16_t len2);

CLICK_CXX_UNPROTECT
#include <click/cxxunprotect.h>
#endif
```

If you allow me I will make these changes, change the existing code, and commit. I also changed the names a little bit, because I think there is no point in leaving ip6 in the names of the data members of the structs.

Glenn Minne

**Comment by kohler** [comment]
I will not approve of these changes.

The `click_ip6` headers are named that way for exact compatibility with other IP6 header definitions, such as this one, from glibc.
http://osxr.org:8080/glibc/source/inet/netinet/ip6.h?v=glibc-2.15

I have a piece of advice. It is very easy, when joining a project, to disagree with every decision the project has made. But that is unwise. The project as a whole encodes about seventeen years' worth of decisions, most of them fine enough. Rarely are your snap decisions going to be radically better. Please take a deep breath and try to *understand* the decisions we have made.

**Comment by glemin** [comment]
But even if glibc uses that decission it doesn't mean it is a better decission.

I disagree with brining arguments as "that is how others do it, and as such we need to do it also that way".

A lot of GNU code is very ugly. That doesn't mean we need to keep that trend as well.

I just want an open discussion about this. Not throwing my proposal away based on dogmas or things that other people do.

Why is that other project doing it the way they do? That is a very valid question. Maybe they don't have a real reason, and is the only reason that it came out historical and people wanted to keep their dogmas high and prevent progressive change. So I first want to know exactly why the other project did it that way then, and why it would be better than using what I proposed.

**Comment by kohler** [comment]
Fine: It is extremely useful for programmers when needless incompatibilities are avoided.

You don't like the name `ip6_hlim`, but that name is used by *literally every UNIX operating system.* It is a **standard name**.
https://www.freebsd.org/cgi/man.cgi?query=ip6&sektion=4&manpath=FreeBSD+5.4-RELEASE

Why? Because it is **defined in an IETF standard**.
https://www.ietf.org/rfc/rfc3542.txt

**Comment by glemin** [comment]
OK, the IETF standard is actually an argument. I don't like that they have chosen it to be that way in the standard, but if they decided, we can't discuss.

I will make a link to that standard in the comment section, so people can view the standard and know that if they want to learn more about the way possible future headers that aren't yet part of it must be included, they can look it up there.
