### ISSUE TITLE
IPRewriter assertion when injecting high-speed traffic

### ISSUE THREAD

**Issue by gkatsikas** [kohler/click#247]
Hi Click folks,

I have been conducting experiments with Click-DPDK, injecting traffic at relatively high rates when I encountered a weird error. When my Click configuration contains an IPRewriter element, which applies some patterns to the src/dst IPs and ports of the incoming packets, I get the following assertion:

click: ../elements/ip/iprewriterbase.cc:250: IPRewriterEntry\* IPRewriterBase::store_flow(IPRewriterFlow_, int, IPRewriterBase::Map&, IPRewriterBase::Map_): Assertion `!old' failed.

When the input rate is around 200.000 packets per second (which is not high at all for Click-DPDK) this occurs for some executions. If I lower the rate all my packets flow through the Click path without problem. If I push at 10Gbps line rate (i.e. 14.88 Mpps for minimum packet size), this happens always.

It seems that there is a kind of race condition in the NAT table which I couldn't manage to nail down yet.

Alternatively, I tried to run my Click-DPDK code using the fast-classifier tool, however I cannot deploy it correctly in DPDK mode. With normal Click, I used to run:
click-fastclassifier -u router.click | <path_to_click>

My system is configured as follows: Linux kernel 3.14 compiled from sources, Click version 3415cd7 and my network cards are 10 Gbit Intel 82599.

Do you have any ideas/suggestions?

Best regards,
Georgios

**Comment by gkatsikas** [comment]
Hi,

The problem was caused because I was pointing multiple FromDPDKDevice (one per queue) to the same instance of IPRewriter. Somehow, packets coming from different cores caused inconsistency in the state of this element. By replicating my IPRewriter across the queues I can make it work.

However, my second question is still valid. How can I transform and run a Click-DPDK configuration using click-fastclassifier and click-devirtualizer?

**Comment by tbarbette** [comment]
Hi,

I never used click-fastclassifier and click-devirtualizer while making the DPDK version. So you're the first to walk on the moon...

Indeed IPRewriter is simply not multithread safe... A simple IPRewriterMP version could be a better solution. While it's not an error to duplicate IPRewriter, if RSS is misconfigured and flow are not ensure to always go through the same queue, it would rewrite the same flow with different flow ids. And I'm not sure what will happen for the reverse path? You'll have to redirect the good flow to the good iprewriter to reverse the modification? Don't think it's even possible...

Tom

**Comment by gkatsikas** [comment]
I agree, the replication does not work for all cases. Stateful Click processors such as NATs might require the same IPRewriter instance to handle more than one queues accounting also the responses. Using the default RSS hashing of Click-DPDK does not guarantee that packets of the same flow will be handled properly in both directions. I am working on this now, I will be back soon.

Regarding the Click tools (fastclassifier and devirtualizer) I will also take a look.

Thanks!
Georgios

**Comment by kohler** [comment]
Closing issue, feel free to reopen.
