### ISSUE TITLE
install error in include/click/packet.hh

### ISSUE THREAD

**Issue by muradkablan** [kohler/click#248]
Hi,
I want to install click with linuxmodule enabled and I'm getting this error when I I try to install it.
I never had this issue before so I'm guessing it might be related to the latest edition to this file in about a month ago?

CXX elements.cc
  CXX click.cc
  LINK click
ln: failed to create symbolic link ‘../bin/click’: File exists
make[1]: [click] Error 1 (ignored)
  INSTALL /home/murad/lib/libclick.a
  INSTALL /home/murad/bin/click
make[1]: Leaving directory `/home/murad/click/userlevel'
make[1]: Entering directory `/home/murad/click/linuxmodule'
make -C /lib/modules/3.19.0/build M=/home/murad/click/linuxmodule  modules
make[2]: Entering directory `/usr/src/linux-3.19'
  CXX [M] nameinfo.o
In file included from /home/murad/click/linuxmodule/../include/click/element.hh:7:0,
                 from /home/murad/click/linuxmodule/../include/click/router.hh:4,
                 from /home/murad/click/linuxmodule/../lib/nameinfo.cc:24:
/home/murad/click/linuxmodule/../include/click/packet.hh: In member function ‘Packet* Packet::data_packet()’:
/home/murad/click/linuxmodule/../include/click/packet.hh:644:16: error: ‘_data_packet’ was not declared in this scope
         return _data_packet;
                ^
make[3]: *** [/home/murad/click/linuxmodule/nameinfo.o] Error 1
make[2]: *** [_module_/home/murad/click/linuxmodule] Error 2
make[2]: Leaving directory `/usr/src/linux-3.19'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/murad/click/linuxmodule'
make: *** [install-linuxmodule] Error 2

**Comment by muradkablan** [comment]
Your commit fix this specific error. But now I have another one

/home/murad/click/linuxmodule/../elements/linuxmodule/fromdevice.cc: In function ‘rx_handler_result_t click_fromdevice_rx_handler(sk_buff**)’:
/home/murad/click/linuxmodule/../elements/linuxmodule/fromdevice.cc:319:56: error: ‘__get_cpu_var’ was not declared in this scope
     if (__get_cpu_var(click_device_unreceivable_sk_buff) == skb)
                                                        ^
make[3]: *** [/home/murad/click/linuxmodule/fromdevice.o] Error 1
make[2]: *** [_module_/home/murad/click/linuxmodule] Error 2
make[2]: Leaving directory `/usr/src/linux-3.19'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/murad/click/linuxmodule'
make: *** [install-linuxmodule] Error 2

**Comment by muradkablan** [comment]
Can you please reopen this issue till we make sure it is resolved?

Murad

**Comment by muradkablan** [comment]
Your commit fixed that specific error. But I got another one. Can you please re-open this issue till this problem fixed?

linuxmodule/../elements/ipsec/ipsecroutetable.cc:74:12: warning: invalid conversion from ‘void*’ to ‘SADataTuple*’ [-fpermissive]
  r.sa_data = NULL;
            ^
  CXX [M] radixipseclookup.o
  CXX [M] satable.o
  CXX [M] sha1.o
  CXX [M] json.o
  CXX [M] anydevice.o
  CXX [M] cyclecountaccum.o
  CXX [M] fastudpsrc.o
  CXX [M] fromdevice.o
/home/murad/click/linuxmodule/../elements/linuxmodule/fromdevice.cc: In function ‘rx_handler_result_t click_fromdevice_rx_handler(sk_buff**)’:
/home/murad/click/linuxmodule/../elements/linuxmodule/fromdevice.cc:319:56: error: ‘__get_cpu_var’ was not declared in this scope
     if (__get_cpu_var(click_device_unreceivable_sk_buff) == skb)
                                                        ^
make[3]: *** [/home/murad/click/linuxmodule/fromdevice.o] Error 1
make[2]: *** [_module_/home/murad/click/linuxmodule] Error 2
make[2]: Leaving directory `/usr/src/linux-3.19'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/murad/click/linuxmodule'

**Comment by muradkablan** [comment]
I'm using Ubuntu 14 with 3.19 kernel if that makes any different.

**Comment by tbarbette** [comment]
This is another error indeed but not related to my commit. Eddie recently made a commit saying the linuxmodule work up to 3.19, I imagine it is not 3.19 included as __get_cpu_var was removed in 3.19.

I think the replacement is the per_cpu macro. You can try to change the usage. A PR after that would probably be much appreciated ;)

**Comment by muradkablan** [comment]
So I just downgraded my kernel to 3.13 and the same Click version I had issues with 3.19 seems to install fine with linuxmodule enabled.  In both cases (3.19 and 3.13) I used the latest Click version.
