### ISSUE TITLE
Receiving side for FastTCPFlows?

### ISSUE THREAD

**Issue by azzamsu** [kohler/click#253]
Hello everyone,

I'm using FastTCPFlows to generate a high-volume, low-latency traffic. And I'd like to know if there is a way to setup a receiving end for the generated traffic. In other words, can I implement a receiver that responds to the SYN/PSH/FIN generated requests?

I'd really appreciate any advice on this.

Azzam

**Comment by bcronje** [comment]
You can have a look at the TCPReflector element https://github.com/kohler/click/blob/master/elements/local/tcpreflector.hh

Since this is in /local you will have to configure click with --enable-local and then recompile.

**Comment by azzamsu** [comment]
That solved it for me. Thanks, Beyers.

**Comment by tbarbette** [comment]
Just by chance, would you have updated this element after finding it? It could use a few configure options.
