### ISSUE TITLE
How to make a subdirectory in the ip6 directory and get the files in there compiled?

### ISSUE THREAD

**Issue by glemin** [kohler/click#259]
What I am trying to do is make a seperate directory inside the ip6 directory for all elements belonging to the IP6Filter I worked on/am working on. 

This might even be only a temporarily directory and not stay in the final design but it works more easily for me while developing if all those files could be located in the same subdirectory of the ip6 directory.

Can anyone explain me how this can be done? Can I just make a subdirectory in the ip6 directory and paste my files in there and will the compiler then be able to find and compile them? Or are there extra steps to be taken in the Makefile maybe? I have looked for documentation on the Makefile but couldn't find it.

**Comment by ahenning** [comment]
Would making a package of your project not be the way to go? Have you looked at the standalone packages like netflow (http://read.cs.ucla.edu/click/packages) or the /click/etc/samplepackage?

**Comment by glemin** [comment]
Thanks a lot! Excellent ideas.

The /click/etc/samplepackage reference was really helpful. The README there and seems to provides all the information I need.
