### ISSUE TITLE
Increasing Packet annotation size

### ISSUE THREAD

**Issue by bcronje** [kohler/click#262]
We are running out of annotation space for our internal use and thinking about doubling anno_size to 96. What would the implications be of doing this apart from the obvious more memory, more data to copy on clone()? I'm assuming there were reasons to originally sticking to 48 bytes?

**Comment by pallas** [comment]
There is no problem increasing the annotation size, as long as you update skbuff.h. That's what I do, and the annotations are statically checked to prevent overlap.

**Comment by bcronje** [comment]
Great, thank you @tbarbette and @pallas exactly what I was hoping for.
