### ISSUE TITLE
Compilation issues with Linux 4.4

### ISSUE THREAD

**Issue by pallas** [kohler/click#270]
After modifying configure.in to allow Linux 4 compilation (PR pending) I'm running into a header modification issue. Specifically, READ_ONCE is creating a union based on `typeof(x)` where `x` is `const seqcount_t*`, creating a union with an uninitialized constant. I've never worked with `linuxmodule/click-linuxtool.pl` rules before but I'm happy to do the work, so any suggestion about how to convert these to non-const would be appreciated.

**Comment by pallas** [comment]
Actually, I should have tried harder first. The following fixes most of the issues..
```--- a/linuxmodule/click-linuxtool.pl
+++ b/linuxmodule/click-linuxtool.pl
@@ -330,6 +330,9 @@ sub one_includeroot ($$) {
            # constant expressions
            s{__cpu_to_be32 *\( *([0-9][0-9a-fxA-FX]*) *\)}{__constant_htonl($1)}g;

+     # de-const typeof in unions
+     s{typeof\(x\)}{typeof(x + 0)}g;
+
            # stuff for particular files (what a shame)
            if ($d eq "page-flags.h") {
                s{(#define PAGE_FLAGS_H)}{$1\n#undef private};```

**Comment by pallas** [comment]
```diff
--- a/linuxmodule/click-linuxtool.pl
+++ b/linuxmodule/click-linuxtool.pl
@@ -333,6 +333,9 @@ sub one_includeroot ($$) {
            # de-const typeof in unions
            s{typeof\(x\)}{typeof(x + 0)}g;

+     # fix illegal void* arithmetic
+     s{(\w+)\s*-\s*\(\s*void\s*\*\s*\)}{(uintptr_t)$1 - (uintptr_t)}g;
+
            # stuff for particular files (what a shame)
            if ($d eq "page-flags.h") {
                s{(#define PAGE_FLAGS_H)}{$1\n#undef private};
```

**Comment by pallas** [comment]
So the last problem I am running into is
```
/home/pallas/click/include/click-linuxmodule/include3/linux/atomic.h: In function 'void atomic_andnot(int, atomic_t*)':
/home/pallas/click/include/click-linuxmodule/include3/linux/atomic.h:469:18: error: 'atomic_and' was not declared in this scope
  atomic_and(~i, v);
                  ^
/home/pallas/click/include/click-linuxmodule/include3/linux/atomic.h: In function 'void atomic64_andnot(long long int, atomic64_t*)':
/home/pallas/click/include/click-linuxmodule/include3/linux/atomic.h:573:20: error: 'atomic64_and' was not declared in this scope
  atomic64_and(~i, v);
```
but I'm not quite sure how to work around it.

**Comment by pallas** [comment]
The issue appears to be
```perl
            s{\band\b}{and_value}g;
```
in `linuxmodule/click-linuxtool.pl`

**Comment by pallas** [comment]
Status update: I have the headers compiling fine. Now I'm dealing with other strange kernel constructs.

**Comment by kohler** [comment]
So thanks to Ubuntu upgrades, I need 4.2 support to investigate #261 further.

I've checked in some changes to that end. I don't have a clean compile yet, but do please look; I had to change some of your #271 diffs.

**Comment by kohler** [comment]
(Interested in your status too!)

**Comment by pallas** [comment]
See #277, although I'm not done yet.

**Comment by kohler** [comment]
I'm going to close this issue and move discussion to #277
