### ISSUE TITLE
C++ 11

### ISSUE THREAD

**Issue by kohler** [kohler/click#276]
I propose to make Click require C++11.

This is a small configuration change, but I know some environments (OpenWRT…?) don't support C++11. But the time has come.

Any comments? @tbarbette @pallas

**Comment by tbarbette** [comment]
I agree ! I always compile with it and have some elements which needs it. Lambda functions are particularly well suited for networking.

I'll check for OpenWRT and friends tomorrow.

**Comment by tbarbette** [comment]
Only problem was this include. It may be resolved with a newer version of uclibc but for the relevance of the feature, I'd say this patch is okay...

**Comment by SDarayan** [comment]
@tbarbette You may want to consider other arch such as arm, mips, and ppc, no?

**Comment by tbarbette** [comment]
It works with all Meraki boards.

@kohler I guess we're okay here.

**Comment by kohler** [comment]
Great, I'm closing the issue. Thanks!
