### ISSUE TITLE
Compliation issue of ClickGUI on Ubuntu 14.04.4 and 16.04 LTS

### ISSUE THREAD

**Issue by czeni** [kohler/click#283]
I tried to install the ClickGUI app after I have sucessfully installed the Click itself I but got the following error (I have experianced the same error on Ubuntu 16.04 and 14.04.4 as well):

> In file included from /usr/local/include/click/config-userlevel.h:295:0,
>                  from /usr/local/include/click/config.h:302,
>                  from gathererror.cc:1:f
> /usr/local/include/click/vector.hh: In instantiation of ‘T& Vector<T>::operator[](Vector<T>::size_type) [with T = GatherErrorHandler::Message; Vector<T>::size_type = int]’:
> gathererror.cc:147:27:   required from here
> /usr/local/include/click/vector.hh:288:5: error: using invalid field ‘Vector<T>::vm_’
>      assert((unsigned) i < (unsigned) vm_.n_);
>      ^
> In file included from gathererror.hh:6:0,
>                  from gathererror.cc:2:
> /usr/local/include/click/vector.hh:289:25: error: using invalid field ‘Vector<T>::vm_’
>      return *(T *)&vm_.l_[i];
>                          ^
> Makefile:437: recipe for target 'gathererror.o' failed
> make[1]: *** [gathererror.o] Error 1
> make[1]: Leaving directory '/home/czentye/click/apps/clicky/src'
> Makefile:421: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1

I am using the latest code from the master branch (git clone --depth 1 https://github.com/kohler/click.git).

BR,
Janos Czentye

[clickgui_error.log.txt](https://github.com/kohler/click/files/388078/clickgui_error.log.txt)

**Comment by kohler** [comment]
Seems like Clicky requires C++11 to compile (not too shocking). I've committed a change to `configure.ac` in 7406d53663f8c51b2721689f2b60b8a30ea0afab. You'll need to re-create and re-run `./configure`, then `make clean; make`. Does that help?

**Comment by czeni** [comment]
It seems yes. 
The compilation was successful and clicky can be started.
Thanks.
