### ISSUE TITLE
click on raspberry

### ISSUE THREAD

**Issue by Roland2014** [kohler/click#302]
Did anybody try and succeed to have click built and running over a raspberry pi (2, 3)?

**Comment by ahenning** [comment]
Userlevel yes, worked well.

**Comment by tbarbette** [comment]
Nice ! It would be interesting to have the story of that somewhere. Is it for personal use? Blog post or something? Or maybe to refresh the Click wiki.

**Comment by Roland2014** [comment]
I agree. Would it be possible to provide detail of what you did to compile for raspberry. First, i can tell that on classic raspbian we do not find system.map that is required to build click binary and for that we need to compiler kernel to have a system.map. Then we can compile click but in our case, it fails. But we tried for building linuxmodule, not userlevel. And perhaps this is the difference!

Thanks for your feedback

**Comment by ahenning** [comment]
Not sure what would be needed to make kernel mode work, but userlevel worked flawless on the Pi. It was used to build a [wan accelerator](http://wanos.co/wan-optimization) for ISPs. The technology works well on the Pi but the CPU was a bit too lightweight to handle reasonable compression levels and deduplication at the required broadband speeds.

What is the requirement for using kernel mode though?

**Comment by Roland2014** [comment]
indeed, to use click we need to git clone the repo and then use configure and then make install. If we do that using --enable-linuxmodule, this builds what is needed to use click as a kernel module (sudo click-install <config>). to get click as a kernel module, you need to have kernel header available at least + other things to be able to build click as a kernel module.

But whatever you do (userlevel with or without enable-linuxmodule option), at build time you need to have system.map file. And we tried on rapsberry 3 and the standard raspbian did not provide. 
As you didn't encounter any issue, it seems your raspberry provides a system.map.
Can you tell us which raspberry and which distribution you used? Did you compile click directly on raspberry or did you cross-compile?
Thanks

**Comment by ahenning** [comment]
Compiled directly on Raspbian. Does "with or without" mean you tried --disable-linuxmodule?

**Comment by bcronje** [comment]
@ahenning is right, you need to explicitly disable linuxmodule via `--disable-linuxmodule` to compile without kernel module.

**Comment by Roland2014** [comment]
Works fine with  `--disable-linuxmodule` to compile only userlevel. Thanks
