### ISSUE TITLE
Vagrant box with click

### ISSUE THREAD

**Issue by amonteilhet** [kohler/click#309]
Hello,

I would like to setup a vagrant box with click already built inside and ready to play for user and kernel mode.

I've already seen that with the latest commit, there is some problems to build the kernel mode with ubuntu with kernel 3 or 4.

Is someone can advice a target OS to build this (and that works in both user and kernel mode) ?

Thank you in advance

**Comment by amonteilhet** [comment]
Finally I managed to build click in kernel mode with an old ubuntu release (14.04 kernel 3.13)

https://atlas.hashicorp.com/amonteilhet/boxes/click_router

**Comment by tbarbette** [comment]
Nice. Is this part of a bigger educational project?

**Comment by amonteilhet** [comment]
Hi Tom. actually I am interested in the subject. I work with to build VNF. I recently tried to attend a coursera MOOC on SDN given by Nick Feamster. It seems to me that click is one of the subjects. For the moment the course is suspended :( So I'm trying to experiment by myself.

Maybe I will try to create a new vagrant box with a recent ubuntu (16.x) and all stuff already built inside (click  for userlevel and kernel mode, and clicky). I think it could be a good starting point to experiment for educational or other purposes (research for instance since I've already seen papers by Nec or Nokia using click software).
