### ISSUE TITLE
Minor issue - License on Click github home page

### ISSUE THREAD

**Issue by bcronje** [kohler/click#314]
I see for some reason GitHub indicates on the home page banner that Click is GPL-2.0 license. This might scare off potential users?

![image](https://cloud.githubusercontent.com/assets/462097/21219733/ac5a0e9a-c2be-11e6-919b-55eb6e90c803.png)

**Comment by kohler** [comment]
I don't know how that's determined or even how to fix it.

**Comment by bcronje** [comment]
Did some digging, according to this [blog post](https://github.com/blog/2252-license-now-displayed-on-repository-overview) GitHub uses a Ruby gem called [Licensee ](https://github.com/benbalter/licensee) to determine which license to display in the project overview page.

It appears that Licensee looks for both COPYING and LICENSE files (among other files) in the repo to determine the license, using either an exact string match or some  Sørensen–Dice coefficient to determine a close match. In Click's case it appears that Licensee is using the COPYING file which obviously relates to the GPL license instead of the LICENSE file. I suspect renaming or moving the COPYING file to something else will probably force Licensee to use the LICENSE file instead.

Your call if you want to spend time on this.
