### ISSUE TITLE
include in config files

### ISSUE THREAD

**Issue by tbarbette** [kohler/click#315]
Hi all,

Is there a way to include a file in a configuration? I may have missed it but I don't think so.

If not, what implementation would you advise? An include element much like define?

`include(common.conf) `

Tom

**Comment by bcronje** [comment]
You can use `require(library common.conf);` which probably does what you want to achieve. See the library bit at http://read.cs.ucla.edu/click/docs/language#requirements

**Comment by tbarbette** [comment]
Nice !  Missed it...
