### ISSUE TITLE
gmake not found after F25 update

### ISSUE THREAD

**Issue by rriggio** [kohler/click#316]
Hi,  after running an update on my f25 distro I start getting this I I try to compile click from a fresh checkout:

`checking for GNU make... not found
checking for working autoconf... found
checking for perl5... no
checking for perl... perl
checking for gawk... gawk
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... (cached) /usr/bin/grep -E
checking for md5sum... md5sum
configure: error:
==============================================

Can't find GNU make.  Either put 'gmake' on your PATH and
rerun './configure', or set the GMAKE environment variable to
GNU make's pathname.

==============================================`

Note, gmake and all the development tools are installed and are working for other projects.

**Comment by tbarbette** [comment]
I confirm the problem on my F25 too.

**Comment by rriggio** [comment]
Very strange, the problem is in this line in the configure:

/bin/sh -c 'make -f /dev/null -n --version | grep GNU' >/dev/null 2>&1

strangely this returns exit code 2, however if I run this

/bin/sh -c 'make -f /dev/null -n --version | grep GNU' >/dev/null

the return code is correctly 0

**Comment by kohler** [comment]
Assuming it's closed!
