### ISSUE TITLE
All click codes always start on CPU core 0 despite other available cores

### ISSUE THREAD

**Issue by kthkaya** [kohler/click#317]
I have several userspace click codes that need to run simultaneously. All the click codes start on the same core (core 0) whereas any other program starts with the affinity list that the linux scheduler provides. This behavior is also restricting the ability to set the affinity of the process that houses the click execution via pyhton code (psutil cpu_affinity()). I tried with and without the -a option but no avail.

Any ideas?
Thanks!

**Comment by tbarbette** [comment]
Bug confirmed, -a is ignored and always on. So the affinity is always changed to 0 for thread 0, ...

I'll solve that, and at the same time change "-a" per "--cpu N", as with the kernel mode. By the time I proposed the -a, I didn't used the kernel mode, but being able to set up an offset in CPU ids is usefull.

**Comment by tbarbette** [comment]
The commit on tbarbette/click branch issue317 solves it. I'll merge that to master as it is small when travis confirms it is passing. I'll make a PR for --cpu.

**Comment by kthkaya** [comment]
Thanks!

**Comment by kthkaya** [comment]
will it be possible to execute --cpu 2,3,4 so that the threads of the click code can make use of other cores? Currently we are trying to generate 500k packets per second with rated source but the core is hogging at %100 and we end up with 70k pps.

**Comment by tbarbette** [comment]
the --cpu=N gives the offset (in Click when the parameter is optional, you have to give a "=" not just whitespace), so if you pass -j 4 --cpu=2, you will use core 2,3,4,5.

Then in Click you have to duplicate your generating element and assign them to threads with StaticThreadSched to different Click threads ids 0,1,2,3 (that will be cores 2,3,4,5).

**Comment by kthkaya** [comment]
Thanks!
I just cloned https://github.com/tbarbette/click.git and installed it with --enable-user-multithread --enable-multithread but I don't see the --cpu option.

**Comment by kthkaya** [comment]
nvm, even though the option doesn't show it works when I pass -j x --cpu=y. Affinity settings is now working. I will now test the functionality 
This was very helpful Tom, thanks a lot!

**Comment by kthkaya** [comment]
I performed some performance tests as following.
There is a simple click router routing between its two interfaces
I have a traffic source (rated source, 50 packet size 100 pps 100 limit) and a traffic sink. I am measuring one way latency of the icmp packets that is routed by the click router via StoreICMPTimeSeqRecord(OFFSET 0, DELTA true)

I performed two tests.
Test 1) Tsource, Tsink and the router are launched without "-j 1 --cpu=1" and thus they all reside on the same core, core 0.

The one way latency through the click router is median 0.05 msec

Test 2) Tsource, Tsink and the router are launched with  "-j 1 --cpu=1" and thus they all reside on the same core, core 1

The one way latency through the click router is median 0.07 msec

Any thoughts?

**Comment by tbarbette** [comment]
Not sure to understand everything but remember that -j1 is the default (therefore giving it or not produce the same result) and the default is not --cpu=0 but "no affinity", meaning that click will be balanced among all cores like any other process. In the first case the load will be balanced among all cores by linux, leading to the result you see I guess

**Comment by kthkaya** [comment]
Yes, I used -j 1 in order to make --cpu argument available.
Then my question is, since the default thread count is 1, how can the click process be balanced among all cores?

**Comment by tbarbette** [comment]
You run multiple Click instance, right? Or I didn't understood correctly. Of course if there is only one click running on one thread, it will not be balanced on multiple cores... But if you gave multiple single thread Click, they will probably run on different CPU.
Maybe try to run your test with --cpu=0 to opt out that thought...

**Comment by kthkaya** [comment]
Yes, I run multiple instances but when I ran them with defaults (no -a or other options), they all get pinned to the same core 0. However you stated that the default is "no affinity" where instances get balanced among cores, which was not the case for me.

**Comment by tbarbette** [comment]
Load balancing on linux systems depends on a lot of things. If isolcpu is still active on cpu 1 it explains why no instance run on that cpu, even if the affinity mask is correct.
But that means it doesn't explain the differences then... Profiling with "perf" tool could help. If your setup involves physical devices, their IRQ may be pinned to core 0, and you would pay a latency drop because of the packet switching core. Just some clues...

**Comment by kohler** [comment]
Is this issue active?

**Comment by kthkaya** [comment]
My initial problem is resolved with Tom's commit. Closing this issue.
