### ISSUE TITLE
Snort-like IDS with Click

### ISSUE THREAD

**Issue by tbarbette** [kohler/click#325]
Hi all,

Does anybody have or know about an implementation of one or a set of elements allowing to run an IDS using Snort-like rules. I would like to compare performances of state-of-the-art solution (Snort, Suricata, ...?) with a pure-Click solution.

As an alternative, someone could have a shared memory system between Click and Snort?

Thanks

**Comment by pallas** [comment]
A `FromHost` (IDS) + `ToHost` (IPS) should do what you want. Are you asking for the actual elements? Or are you asking for something that implements Snort rules? My suggestion would be to just use Snort or Suricata since they contain so much state. It should be possible to implement something efficient in DAQ but I don't know of any public implement that does this, e.g. via netmap.

**Comment by tbarbette** [comment]
I should have mentionned the userlevel context^^ Moreover even with ToHost/FromHost there is quite a big penalty. 

Essentially there is two options : 
* Bring Snort functionnality inside Click in a big (or a set of) elements. Multiple recent papers claim having done something similar, sometimes even with Snort rulesets, though I imagine in practice their elements do not implement all Snort features.
* Send packets to Snort ideally using a shared-memory technique. Or while still unavailable, use kernel interfaces with ToHost/KernelTAP or a DPDK KNI interface which is essentially zero copy of DPDK packets from and to the kernel, but there would still be a useless copy to go back to userlevel for Snort.

We've got a master student working on a proper Snort DAQ to use DPDK rings (essentially shared memory between DPDK applications, like Click). But I'm in a bit of a hurry and I was wondering if someone had already done something like either of those solutions, and would be willing to share their work.

**Comment by pallas** [comment]
I think you're right that DAQ/DPDK glue or DAQ/netmap glue is the right approach, but I don't have an implementation of that. :(

**Comment by tbarbette** [comment]
Well, we'll make DPDK Ring DAQ then.
