### ISSUE TITLE
Segmentation fault (core dumped) in ipfilter

### ISSUE THREAD

**Issue by labiyouxiaoxin2** [kohler/click#341]
Hi, I want to use click to implement a firewall filter. I followed the instructions in IPFilter Element Documentation and used it like this :  ipf::IPFilter( allow src 1.0.2.36, deny all), which  triggered
segmentation fault (core dumped). However if I change "deny all" to "allow all", it is OK. Is it normal? Why＂allow "and "deny" can not be used at the same time?
Look forward to your reply. Thank you!

**Comment by tbarbette** [comment]
What is the configuration around the ipfilter?
Usually segfault happen when you use an IP element without the ip header annotation set. Did you put a CheckIPHeader before?

**Comment by labiyouxiaoxin2** [comment]
(1)The configuration around the ipfilter is as follows:

ipf::IPFilter(
allow src 1.0.2.36,
deny all,   //  It  triggered segmentation fault (core dumped)
allow all   //it is OK );

t::TimestampAccum;
c::Counter;
RandomSource(64, LIMIT 1000, STOP true) ->SetTimestamp-> ipf->t->c->Discard;

(2)I didn't put CheckIPHeader.

**Comment by labiyouxiaoxin2** [comment]
Thank you very much for your reply. My problem has been resolved with CheckIPHeader/or MarkIPHeader. Thanks for your help!
