### ISSUE TITLE
Is any example of CLICK configuration with DPDK available?

### ISSUE THREAD

**Issue by wtao0221** [kohler/click#347]
@tbarbette 
Hi, Tom,

Is there any example of CLICL configuration with DPDK, to implement a IP router?

The make-ip-conf.pl may not work with DPDK?

**Comment by tbarbette** [comment]
You can find example in the FastClick repository (tbarbette/fastclick), they are mostly compatible with the mainline DPDK.

Normally you only need to change the FromDevice per FromDPDKDevice elements after generating the configuration, but you need to set up DPDK as per the DPDK doc before. If you go multi-thread, the mainline version needs you to play with multi-queue yourself or use good old locks. I strongly suggest starting with 1 core, then move to multiple one.

**Comment by wtao0221** [comment]
@tbarbette 
Hi, Tom,

Since ToDPDKDevice is push-mode, it is not possible to concat a Queue element right before the ToDPDKDevice element.

So how can we implement a queue scheduling algorithm here?

**Comment by tbarbette** [comment]
I made the Pipeliner element which is essentially a full-push queue performing much better than a Queue->Unqueue would. But it seems that I never got the mainline version through... 
The branch is here https://github.com/tbarbette/click/tree/PRPipeliner I guess there was some work left to do but it should be good to go.

**Comment by wtao0221** [comment]
@tbarbette 

Sorry to disturb you again, it reports that /usr/bin/ld can't find -lethdev and -lrte_pmd_virtio_uio. I have correctly installed DPDK.

**Comment by tbarbette** [comment]
Which version of DPDK do you use? Do not use the latest git tree, first because I need to make changes for each version to compile and second because there is no stability insurances for DPDK main tree and it is actually not very stable. 17.02 should be fine.
