### ISSUE TITLE
when i try to install click i get this error 

### ISSUE THREAD

**Issue by peterrz** [kohler/click#351]
`make `
`make[2]: *** [string.bo] Error 1 `                               
`make[2]: Leaving directory /home/peter/openwrt/trunk/click/tools/lib'   `
`make[1]: *** [lib] Error 2    `                                
`make[1]: Leaving directory /home/peter/openwrt/trunk/click/tools '  `
`make: *** [tools] Error 2   `

**Comment by tbarbette** [comment]
Could you provide the command, the ./configure line, more info about the environment ,etc?
Thanks

**Comment by peterrz** [comment]
Hi,
When i Try run this config :
` ./configure  --disable-app-fuzzer --disable-app-performance --disable-app-sniffer --enable-app-tunnel --disable-app-stats --disable-doc --disable-doc-man --enable-local --enable-userlevel --enable-wifi  --host=mips-unknown-elf --build=mips --prefix=/home/peter/openwrt/trunk/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/ --with-linux=/home/peter/openwrt/trunk/build_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/linux`
 
in processes of confining show me this error 

> Can't find Linux System.map file /nonexistent_file,
> so I won't compile the linuxmodule driver.
> (You may need the --with-linux=DIR and/or --with-linux-map=MAP options.)

seems like problem is with this line `--with-linux=/home/peter/openwrt/trunk/build_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/linux`  cause there is no sub-folder _/linux_ at this directory.
I hope you reply.

**Comment by peterrz** [comment]
problem was solved at #340 , add this code to lib/error.cc manually, 
add them to line 726.

`s = s2 + 1; 
for (Conversion *item = error_items; item; item = item->next)
if (item->name.equals(s1, s2 - s1)) {
+#ifdef HAVE_VA_LIST_AS_ARRAY
+		    strstore = item->hook(flags, (va_list*) VA_LIST_REF(val));
+#else
    strstore = item->hook(flags, VA_LIST_REF(val));
+#endif
 s1 = strstore.begin();
s2 = strstore.end(); 
 goto got_result;`
[link](https://github.com/kohler/click/pull/340/files)
