### ISSUE TITLE
Question about monitoring

### ISSUE THREAD

**Issue by peterrz** [kohler/click#361]
Hi, 
i'm new at click ,i want monitoring performance, any available  element or function ? please guide me.

**Comment by bcronje** [comment]
Try some of the [Counters elements](http://read.cs.ucla.edu/click/elements#counters)

If you want packets per second, bit rate and packet count type stats use [Counter](http://read.cs.ucla.edu/click/elements/counter) 

Counter exposes all those stats via read handlers. You can read them via [ControlSocket ](http://read.cs.ucla.edu/click/elements/controlsocket) or proclikefs (if linux module). Or you can use a Script element to print to console. Here is an example using Script:

```
FromDevice(eth0) -> c1::Counter -> Queue -> ToDevice(eth1);
Script ( 
        printn "c1 Bit Rate ",
        printn c1.bit_rate,
        printn " Count ",
        printn c1.count,
        printn " Bytes ",
        print c1.byte_count,
        wait 2,
        loop
        )
```

**Comment by tbarbette** [comment]
I personnaly like AverageCounter that gives you a rate.

Beware of mutli-thread (un)safeness with all of those.

**Comment by peterrz** [comment]
@bcronje 
@tbarbette 
thanks to guide me, is it capable in Access points ?
i want send information to controller floodlight and also i want dynamic period report. any solutions ? (this dynamic report time should be set on controller )

**Comment by peterrz** [comment]
how i can debug my code before running on my router ? any debugger available ?

**Comment by ahenning** [comment]
click_chatter works as a starting point

**Comment by peterrz** [comment]
@ahenning thank you,
Please describe more,

**Comment by ahenning** [comment]
Look at click_chatter examples in the existing click elements

**Comment by bcronje** [comment]
As @ahenning  said for basic help click_chatter is like printf. If you want full debugger support then just use gdb and run Click in userlevel mode. Personally I use KDevelop as my IDE for Click development and it supports gdb with a nice GUI for debugging.

**Comment by peterrz** [comment]
@bcronje thanks!
