### ISSUE TITLE
Fail to build under rump when it tries to build BUILD_CXX

### ISSUE THREAD

**Issue by AlanYiNew** [kohler/click#363]
Does Click always try to build its own library instead of stl

**Comment by tbarbette** [comment]
Hi Alan,

Click never uses STL, because the Kernel mode can't. I guess the error you're seeing is related to something else but you're not very extensive on details... Most needed piece of the STL has been re-implemented from scratch.

Tom

**Comment by pallas** [comment]
Please post the error log as text.

**Comment by AlanYiNew** [comment]
Can you please close the thread. It turns out to be that I forgot to set the cross platform parameter when configuring. Really Sorry for this
