### ISSUE TITLE
checkpaint.cc doesn't behave as documents say

### ISSUE THREAD

**Issue by AlanYiNew** [kohler/click#373]
According to the document packet is always pushed to port 0 when redirect , the copy will be pushed through port1 as well. Right now packet is pushed through either port based on color. Am I wrong?

**Comment by bcronje** [comment]
The documentation states correctly: 

> Checks that incoming packets have paint annotation equal to COLOR. If their paints are not equal to COLOR, then they are dropped or emitted on output 1, depending on how many outputs were used. CheckPaint uses the packet's PAINT annotation by default, but the ANNO argument can specify any one-byte annotation.

In other words, if the color matches it will emit on port 0, if it doesn't match it will emit on port 1 if it exists otherwise it will be dropped.

**Comment by ahenning** [comment]
If you are want a copy you can use Tee after the checkpaint to clone the packet. Then there are two and you can forward the original packet and process the cloned packet with different elements.
