### ISSUE TITLE
Add wiki for clickunderhood

### ISSUE THREAD

**Issue by banmoy** [kohler/click#383]
@kohler Can you add the clickunderhood page to the wiki?

**Comment by peterrz** [comment]
hi, i hope this help you [clickunderhood [Click].pdf](https://github.com/kohler/click/files/1567050/clickunderhood.Click.pdf)

**Comment by banmoy** [comment]
It helps me a lot. Thanks very much.

**Comment by kohler** [comment]
I have also imported a version of that page to the current Wiki:

https://github.com/kohler/click/wiki/Click-Under-the-Hood
