### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by banmoy** [kohler/click#385]
When building click, I got the error
```
 make[1]: *** No rule to make target '../elements/local/pad.cc', needed by 'pad.o'.  Stop.
 make[1]: Leaving directory '/home/lpf/click-master/userlevel'
 make: *** [userlevel] Error 2
```
I use centos7 and my configure setting is
`./configure --enable-user-multithread --enable-all-elements --enable-local`

Can someone help me?

**Comment by ahenning** [comment]
pad.cc is your custom element and you need help to compile this element?

If so can you upload the contents of pad.cc and pad.hh?

**Comment by tbarbette** [comment]
Don't add --enable-all-elements or --enable-local unless you need them. Also pass --disable-linuxmodule (or is it implied by user-multithread)?

**Comment by banmoy** [comment]
@ahenning pad.cc is not my custom element. I just find the file under elements/standard.

**Comment by banmoy** [comment]
@tbarbette I try the configuration `./configure --enable-user-multithread --disable-linuxmodule`, but it does not work.

**Comment by ahenning** [comment]
`make[1]: *** No rule to make target '../elements/local/pad.cc', needed by 'pad.o'.  Stop.`

Sure there is not a version of that file in elements/local/ ?

**Comment by bcronje** [comment]
As @tbarbette said, all you would need is `./configure --enable-user-multithread --disable-linuxmodule`. And then the normal make.

**Comment by banmoy** [comment]
@ahenning I use the newest master code, and there is no pad.cc in elements/local.

**Comment by banmoy** [comment]
@bcronje I have tried again, and got the same error.

**Comment by tbarbette** [comment]
A clean and rebuild of elements list?
`make clean && make distclean && make elemlist`

**Comment by banmoy** [comment]
@tbarbette It works. Thanks very much.
