### ISSUE TITLE
Failed to compile the kernel module

### ISSUE THREAD

**Issue by daehyeok-kim** [kohler/click#394]
On Ubuntu 16.04 with kernel 4.4.0-116-generic, I tried to compile the click kernel module with the following command:
`./configure --enable-linuxmodule --with-linux=/usr/src/linux-headers-4.4.0-116-generic --with-linux-map=/boot && sudo make install`

I got the following compile error:
`/extra_disk/click/linuxmodule/../elements/linuxmodule/fromhost.cc:143:50: error: macro "alloc_netdev" requires 4 arguments, but only 3 given
     net_device *dev = alloc_netdev(0, name, setup); `

It looks like fromhost.cc follows the macro (alloc_netdev) definition in old versions of the kernel.
Is there any patch for this issue? 

Thanks!

**Comment by stevelorenz** [comment]
@daehyeok-kim Hello, I have the same issue to compile click kernel module. Could you give me some information to solve this issue? Thanks in advance for the help.
