### ISSUE TITLE
Unable to access information on http://www.read.cs.ucla.edu/click/routetabletest-167k.click.gz

### ISSUE THREAD

**Issue by TummanapallyAnuraag** [kohler/click#415]
Command: man IPRouteTable

In line 49, following is written:

A       Click       script       containing       the       167000-route       dump       is       available       at
       http://www.read.cs.ucla.edu/click/routetabletest-167k.click.gz

Unfortunately the link is not opening, can i get an alternative source for this?
Thanks

**Comment by pallas** [comment]
That server is dead and never coming back.

~Derrick • iPhone

**Comment by TummanapallyAnuraag** [comment]
Any Idea where i can get that file?

**Comment by tbarbette** [comment]
Did you manage to find it ?

**Comment by TummanapallyAnuraag** [comment]
No, I couldn't find it...

**Comment by pallas** [comment]
That site is dead and gone.

~Derrick • iPhone

**Comment by tbarbette** [comment]
> That site is dead and gone. ~Derrick • iPhone

Yes but someone may have kept the file.

@TummanapallyAnuraag  it seems lost, I would suggest you close the issue then...

**Comment by kohler** [comment]
Always remember the existence of archive.org. That site has a snapshot of the file, which you can find by entering the url.

**Comment by kohler** [comment]
https://web.archive.org/web/*/http://www.read.cs.ucla.edu/click/routetabletest-167k.click.gz

**Comment by TummanapallyAnuraag** [comment]
Thanks, that solves my issue!

**Comment by tbarbette** [comment]
I re-uploaded the file to the wiki and changed the link (https://github.com/kohler/click/wiki/files/routetabletest-167k.click.gz) . I'll update the main repository in iproutetable.hh as soon as I'll finish to fix travis (they are not always supporting AVX2, which makes DPDK fail to build).
