### ISSUE TITLE
test-ping-userlevel.click on VM

### ISSUE THREAD

**Issue by Azure-kyLIN** [kohler/click#420]
I try to learn click through easy example in conf
And now I successfully get through three test.click but got trouble in **test-ping-userlevel.click**
My environment is Ubuntu Virtual Machine 14.04 with kernel 4.4.0-31
Each time I try to run this program it returns with
```code
./conf/test-ping-userlevel.click:22: While configuring 'FromDevice@1 :: FromDevie':
bad Method
Router could not be initialized!
```
Can anybody give more details about this error? Thanks a lot!!

**Comment by tbarbette** [comment]
The default method of that file is PCAP. Did you configure and compiled with libpcap-dev installed ?
