### ISSUE TITLE
How large Routing Tables can click handle.

### ISSUE THREAD

**Issue by TummanapallyAnuraag** [kohler/click#423]

**Comment by TummanapallyAnuraag** [comment]
I have tried to use 100,000 (1 Lakh) entries in routing table of click, but the destination address couldn't be parsed by the router (my PC). Can i know the maximum limit of the routing table for this purpose.
Thanks in advance.

**Comment by tbarbette** [comment]
Which element are you speaking about? There are multiple different routing table implementations. This is discussed in the wiki page of one of those elements I think.

Technically there is no limit... Just the amount of memory. The resulting lookup speed would be more what you're looking for.

**Comment by TummanapallyAnuraag** [comment]
Thanks @tbarbette for prompt reply.
I was using `StaticIPLookup` element.
After checking again, it seems that it take long time to configure the element.
for 10000 entries it took me around 4 minutes.
So, if i wait long enough will i be able to handle 100,000 entries?

**Comment by senjoo** [comment]
In a single threaded click with moderate traffic (500kpps), I've found only RadixIPLookup handles route ingestion in a manner that doesn't affect traffic (700k+ routes) and does so in a reasonable time period (sub-30 seconds).  The others cause considerable packetloss during ingestion, and some of them (sorry I don't remember specificly) just fall apart when doing 500kpps.

The other route table elements may operate better if using separate threads....haven't played around with them in that configuration.

**Comment by TummanapallyAnuraag** [comment]
Thanks @senjoo for the information.
