### ISSUE TITLE
Hot-swapping:

### ISSUE THREAD

**Issue by sakuraliyi** [kohler/click#432]
Hi, now I want to know more about hot-swapping. I read The Click Modular Router and search for a long time, but I only find a little information. I want to know the principle of hot-swapping and its use. And in user-level, can hot-swapping run in option -r(I failed) ? If you have some useful information, please tell me. Thanks!

**Comment by tbarbette** [comment]
Did you find what you looked for ? It is true that is a non very well documented function especially for userlevel. Feel free to update the wiki with your conclusions.

**Comment by bcronje** [comment]
Hotswapping is userlevel is definitely supported. Will see if I cant post some more detail when I get a chance.
