### ISSUE TITLE
ProtocolTranslator Question

### ISSUE THREAD

**Issue by ap1636** [kohler/click#433]
Hi, 
I'm new to click. And trying to use ProtocolTranslator https://github.com/kohler/click/wiki/ProtocolTranslator46 
But on page in description ita says it has 2 input and outputs. Will someone help me to give any example of how to use it. 
 Can I directly use it as , Fromdevice->ProtocolTranslator46 ??

**Comment by tbarbette** [comment]
Hi,

You should probably start by following a few Click tutorials. You're asking how to use the rear speed without knowing how to drive the car.

Tom
