### ISSUE TITLE
RatedSource userlevel high CPU 

### ISSUE THREAD

**Issue by ppatel826** [kohler/click#435]
I wrote a simple rated traffic generation using RatedSource element. The click config generated 100KBps UDP traffic. When I ran that in userlevel the single core CPU ran at 100% until that packet generation LIMIT was reached. Is this normal? How can I optimize for traffic generation?

**Comment by tbarbette** [comment]
What is the downstream pull to push element ?  If it does not support notifications it will pull endlessly.

**Comment by ppatel826** [comment]
Pull Element. Which downstream element you can recommend to achieve high data rate traffic stimulation?

**Comment by ppatel826** [comment]
Following is sample configuration. 
![image](https://user-images.githubusercontent.com/34899745/56329442-826df400-6151-11e9-97f6-052b396d55ce.png)

**Comment by ppatel826** [comment]
Fixed it by adding PullNull
