### ISSUE TITLE
error: SIOCGSTAMP

### ISSUE THREAD

**Issue by JackokieZhao** [kohler/click#460]
It occurs the error "SIOCGSTAMP" when I make the click project for NS3.

Here is the make command:
`$ git clone https://github.com/kohler/click
$ cd click/
$ ./configure --disable-linuxmodule --enable-nsclick --enable-wifi
$ make`

The following is the output log.
`ar: `u' modifier ignored since `D' is the default (see `U')
  RANLIB libclick.a
  CXX ../elements/userlevel/fromdevice.cc
../elements/userlevel/fromdevice.cc: In member function ‘virtual void FromDevice::selected(int, int)’:
../elements/userlevel/fromdevice.cc:546:49: error: ‘SIOCGSTAMP’ was not declared in this scope
      p->timestamp_anno().set_timeval_ioctl(_fd, SIOCGSTAMP);
                                                 ^~~~~~~~~~
../elements/userlevel/fromdevice.cc:546:49: note: suggested alternative: ‘SIOCGRARP’
      p->timestamp_anno().set_timeval_ioctl(_fd, SIOCGSTAMP);
                                                 ^~~~~~~~~~
                                                 SIOCGRARP
make[1]: *** [elements.mk:404: fromdevice.o] Error 1
make[1]: Leaving directory '/home/jackokie/Work/NS3/click/userlevel'
`

**Comment by woma1029** [comment]
If your Kernel version is >= 5.2 , there's an open pull request that solved the problem for me :
https://github.com/kohler/click/pull/451/commits/ef8c838a0f8abdd791182ec9c480528f0afb7fbe

**Comment by tbarbette** [comment]
Merged
