### ISSUE TITLE
Configure failed on debian-buster due to click-linuxtool.pl execution failure

### ISSUE THREAD

**Issue by swapniil** [kohler/click#463]
`./configure --enable-user-multithread=yes  --with-linux=/usr/src/linux-headers-4.19.0-10-common --enable-select=poll --enable-ip6 --enable-task-heap  --enable-intel-cpu CXXFLAGS=-std=gnu++11 --with-linux-map=/boot/System.map-`uname -r``
> > checking for Linux kernel compilation flags...   -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__       -fno-strict-aliasing  -fshort-wchar    -fno-PIE -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup  -mno-red-zone -mcmodel=kernel -funit-at-a-time  -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe  -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks      -O2 --param=allow-store-data-races=0       -fomit-frame-pointer  -fno-var-tracking-assignments         -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack      -fmacro-prefix-map=./=     
> configure: making C++-safe versions of Linux kernel headers (may take a while)
> Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/(typedef\s+struct[^\}]+)(struct\s+__raw_tickets\s+)({ <-- HERE [^\}]+})/ at /home/swapnil/click/./linuxmodule/click-linuxtool.pl line 428.
> ./include/linux/fs.h: 0), 	 [__magic_struct_kiocb.ki_filp = filp;
> __magic_struct_kiocb.ki_flags = iocb_flags(filp);
> __magic_struct_kiocb.ki_hint = ki_hint_validate(file_write_hint(filp));
> __magic_struct_kiocb.ki_ioprio = IOPRIO_PRIO_VALUE(IOPRIO_CLASS_NONE;
> ] (3) at /home/swapnil/click/./linuxmodule/click-linuxtool.pl line 221.
> configure: error: 
> ==============================================
> 
> click-linuxtool.pl execution failed.
> 
> ==============================================
> 

This is happening due to RegX applied in file.

**Comment by swapniil** [comment]
Its a small fix.
Can somebody direct me to the page where I can understand procedure to raise a review request.

**Comment by tbarbette** [comment]
You just do like any github pull request, I guess :)
