### ISSUE TITLE
Router initialization failed

### ISSUE THREAD

**Issue by p4pe** [kohler/click#466]
Hello,

I installed ClickOS following this [tutorial](https://clickosblog.wordpress.com/2018/08/24/installing-clickos-for-xen-hypervisor/)

And I tried to run a simple example with FastUDPSource element.. The router initialization. 

<img width="311" alt="fast" src="https://user-images.githubusercontent.com/35313995/95734707-7dc5c580-0c8c-11eb-84db-8be405ab6f9c.png">

My .click file configuration is:
FastUDPSource(100000,500000, 60, 00:00:00:00:00:02, 10.10.10.2, 1234, 00:00:00:00:00:03, 10.10.10.3, 1234)->ToDevice()

**Comment by tbarbette** [comment]
FastUDPSource was not compiled. I'm not sure there is a version for minios. Though I don't see why the userlevel version would not work. You can try removing "ELEMENT_REQUIRES(userlevel)" in elements/userlevel/fastudpsrc.cc:266, then  make clean && make and see what happens.

**Comment by p4pe** [comment]
There is no fastudpsrc.cc.226 in the userlevel directory.. only in linuxmodule directory. This element only works(?) in kernel module.

**Comment by tbarbette** [comment]
It's in elements/userlevel, not userlevel ;)

**Comment by p4pe** [comment]
@tbarbette  We said the same ;)
<img width="945" alt="elmeents" src="https://user-images.githubusercontent.com/35313995/95746070-dd2cd100-0c9e-11eb-950b-d4b6fbd88345.png">

**Comment by tbarbette** [comment]
https://github.com/kohler/click/blob/master/elements/userlevel/fastudpsrc.cc ? Are you on some old commit/branch?

**Comment by p4pe** [comment]
I followed this [tutorial](https://clickosblog.wordpress.com/2018/08/24/installing-clickos-for-xen-hypervisor/) for the installation

**Comment by p4pe** [comment]
@tbarbette did i do something wrong?

**Comment by p4pe** [comment]
Thank you @tbarbette, now  I installed and use the userlevel click. Next step is to use along with DPDK

**Comment by tbarbette** [comment]
Did you want to use Click OS specifically? Or just any version of Click is okay?
If you don't need the virtualization, Click+DPDK is the way to go for sure. And maybe even inside containers with SRIOV for performance that is largely adopted now (More than lightweight VM such as MiniOS/ClickOS). 
Note the DPDK version in mainline Click is limited, if you want state of the art performance try FastClick.

**Comment by p4pe** [comment]
Thanks  for the feedback @tbarbette . Are you aware of any tutorial/material on coupling DPDK with Click?

**Comment by tbarbette** [comment]
This applies to DPDK for both Click and FastClick, just that with Click the multiqueing must be done manually and you won't have batching: https://github.com/tbarbette/fastclick/wiki/High-speed-I-O#dpdk

And a general tutorial, works for both too : https://github.com/tbarbette/fastclick/wiki/Tutorial

**Comment by p4pe** [comment]
Thanks! Probably I have to take a look on how DPDK works, because i am newbie!
