### ISSUE TITLE
ΙPSec in Click/UserLevel

### ISSUE THREAD

**Issue by p4pe** [kohler/click#470]
Hello Im trying to create a simple IPSec click router with the corresponding elements(IPsecESPEncap, IPsecAuthSHA1 .. etc), but I realize that these elements are not available.

Are these elements only available in kernel mode?

**Comment by gkatsikas** [comment]
You should configure Click with: --enable-ipsec

**Comment by p4pe** [comment]
Thank you @gkatsikas
