### ISSUE TITLE
How to comunication beetwen Elements

### ISSUE THREAD

**Issue by ali64mohammad** [kohler/click#484]
Hi
my Question is how Elements can interact with each other
for example suppose I have two elements in front of two different interfaces, for example, I want to get IP and mac of every input packet of the first element and send just send IP and mac (not whole packet) to the second element to use them.
and the first element is kind of transparent and it is just for monitoring so the origin packet should be sent to its destination without any change.
my focus is on element communication without sending packets between them. for example how can parse a packet in an Element and use parsed packet object in another element.
thanks.

**Comment by tbarbette** [comment]
You could use handlers, but the most efficient way would be to pass the element as an argument to the other element (just parse an Element* variable in configure()), and then cast it to your element class, and access the members directly or call functions.

**Comment by ali64mohammad** [comment]
thanks for answer.
is there any example for this solution?

> You could use handlers, but the most efficient way would be to pass the element as an argument to the other element (just parse an Element* variable in configure()), and then cast it to your element class, and access the members directly or call functions.

**Comment by tbarbette** [comment]
ARPQuerier takes an ARPTable element as parameter : 

```
 .read("TABLE", ElementCastArg("ARPTable"), _arpt)
```

Then you have normal C++ function calls like : 
```
_arpt->set_timeout(timeout);
```

**Comment by ali64mohammad** [comment]
thanks you so much.

**Comment by tbarbette** [comment]
If the sequence is always the same, like element A is followed by B and there's only one of each, you can automatically find the downstream/upstream elements
```
ElementCastTracker track(router(), "B");
router()->visit_downstream(this,0,&track);
```
