### ISSUE TITLE
Unit test for Elements

### ISSUE THREAD

**Issue by ali64mohammad** [kohler/click#486]
Hi, I Implemented a Click Element and now I want to write a unit test for it. this element just for monitoring so just store some information from the packet and send a packet to output without any changes. so tests should be base on information that stores in the element. for example, my element stores  IP address, in the test I will send a packet with a specific IP address and then the unit test should check that the IP address is equal to a stored IP address in the element. 
is there any unit test tool that I can test my Element with it?
I saw some clicktest files is there any documentation for them?
thanks.

**Comment by tbarbette** [comment]
Try "man clicktest" if you have installed Click with make install.

But basically you can run "make check" that will launch all clicktest files in the test folder. You can find a test that does a bit of what you asked, duplicate that one and start from there :)

Some elements need some C++ code for testing, so the clicktest files reference a testing element that usually resides in elements/test/. There also you can try to duplicate one and start from there.

**Comment by ali64mohammad** [comment]
Thanks.
