### ISSUE TITLE
chaning .click file dynamicly

### ISSUE THREAD

**Issue by ali64mohammad** [kohler/click#490]
Hi
is it possible to change .click config and apply changes without rerunning click.

**Comment by ahenning** [comment]
Yes, see https://github.com/kohler/click/issues/459

**Comment by ali64mohammad** [comment]
if i understand correctly hotconfig is for changing config in element.(?)
but i mean for example change this file:

```
PollDevice(eth1, true)
  -> SetTimestamp
  -> Queue(8)
  -> DelayShaper(10)
  -> BandwidthShaper(131072B/s) // 1Mb
  -> ToDevice(eth2);

PollDevice(eth2, true)
  -> SetTimestamp
  -> Queue(8)
  -> DelayShaper(10)
  -> BandwidthShaper(131072B/s) // 1Mb
  -> ToDevice(eth1);
```

and change it for example like this:

PollDevice(eth1, true)
  -> ToDevice(eth2);

PollDevice(eth2, true)
  -> ToDevice(eth1);

and apply changes with out restarting click.
this is possible with hotconfig?

**Comment by tbarbette** [comment]
Yes. Except the second configuration is not correct :p

**Comment by ali64mohammad** [comment]
it was just for example, Thanks
